import express from 'express';
import cors from 'cors';
import crypto from 'crypto';
import { supabase } from './supabase';
import { ALL_SYSTEM_PERMISSIONS, getUserById, getUserByEmail, listUsers, listDepartments, getOrCreateDepartment, createDepartment, updateDepartment, listBosses, getBossById, createBoss, updateBoss, deleteBoss, listRoles, createRole, updateRole, getPopulatedRequests, getRequest, insertRequest, updateRequest, deleteRequest, generateNextFolio, createApprovalToken, validateApprovalToken, processApprovalTokenAction, recordAuditLog, listAuditLogs, createVerificationCode, verifyCodeAndActivateUser, hashPassword, verifyPassword, sanitizeUser, hasPermission } from './db';
import { buildBossApprovalEmailHtml, buildSystemsApprovedEmailHtml, buildVerificationEmailHtml, buildNewAccountAdminEmailHtml, buildTokenApprovalResultPageHtml, sendEmail, getFromAddress, outboxLogs } from './mailService';
import type { User, Role, TravelRequest, StoredUserRecord } from '../src/types';

function baseUrl(req:express.Request){const configured=process.env.APP_URL?.trim().replace(/\/+$/,'');if(configured&&!(process.env.VERCEL&&configured.includes('localhost')))return configured;if(process.env.VERCEL_PROJECT_PRODUCTION_URL)return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;if(process.env.VERCEL_URL)return `https://${process.env.VERCEL_URL}`;const host=req.headers['x-forwarded-host']||req.headers.host;const proto=String(req.headers['x-forwarded-proto']||'http').split(',')[0];return host?`${proto}://${host}`:'http://localhost:3000';}
function parseCookies(req:express.Request){const raw=req.headers.cookie||'';return Object.fromEntries(raw.split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))];}));}
function jwtSign(payload:Record<string,unknown>){const secret=process.env.JWT_SECRET;if(!secret)throw new Error('Falta JWT_SECRET');const enc=(v:string)=>Buffer.from(v).toString('base64url');const head=enc(JSON.stringify({alg:'HS256',typ:'JWT'}));const body=enc(JSON.stringify({...payload,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+8*60*60}));const sig=crypto.createHmac('sha256',secret).update(`${head}.${body}`).digest('base64url');return `${head}.${body}.${sig}`;}
function jwtVerify(token:string){const secret=process.env.JWT_SECRET;if(!secret)throw new Error('Falta JWT_SECRET');const p=token.split('.');if(p.length!==3)throw new Error('JWT inválido');const expected=crypto.createHmac('sha256',secret).update(`${p[0]}.${p[1]}`).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(p[2])))throw new Error('JWT inválido');const payload=JSON.parse(Buffer.from(p[1],'base64url').toString('utf8'));if(!payload.exp||payload.exp<Math.floor(Date.now()/1000))throw new Error('Sesión expirada');return payload as {sub:string};}
async function auth(req:express.Request){const cookies=parseCookies(req);const bearer=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();const token=cookies.dimer_session||bearer;if(!token)return null;try{const p=jwtVerify(token);const u=await getUserById(p.sub);if(!u||u.status!=='ACTIVO')return null;const roles=await listRoles();return sanitizeUser(u,roles.find(r=>r.id===u.roleId));}catch{return null;}}
function requireAuth(req:express.Request,res:express.Response,next:express.NextFunction){void auth(req).then(u=>{if(!u)return res.status(401).json({error:'Autenticación requerida'});(req as any).dimerUser=u;next();}).catch(()=>res.status(503).json({error:'Base de datos no disponible'}));}
function requirePermission(permission:any){return (req:express.Request,res:express.Response,next:express.NextFunction)=>{const u=(req as any).dimerUser as User|undefined;if(!hasPermission(u,permission))return res.status(403).json({error:'No tienes permiso para esta operación'});next();};}
function err(res:express.Response,e:unknown){const msg=e instanceof Error?e.message:'Error interno';const status=/JWT|autentic|token inválido|no se encontró/i.test(msg)?400:503;return res.status(status).json({success:false,error:msg});}

export function createApp(){const app=express();app.set('trust proxy',1);app.use(cors({origin:true,credentials:true}));app.use(express.json({limit:'10mb'}));
app.get(['/api/health','/health'],async(_req,res)=>{try{const {error}=await supabase.from('users').select('id',{head:true,count:'exact'});if(error)throw error;res.json({ok:true,service:'viaticos-dimer-api',database:'supabase',runtime:process.env.VERCEL?'vercel-serverless':'node',timestamp:new Date().toISOString()});}catch(e){res.status(503).json({ok:false,database:'supabase',error:'Database unavailable'});}});
app.get(['/api/diagnostic','/diagnostic'],async(_req,res)=>{try{const [u,r]=await Promise.all([supabase.from('users').select('id',{head:true,count:'exact'}),supabase.from('travel_requests').select('id',{head:true,count:'exact'})]);if(u.error)throw u.error;if(r.error)throw r.error;res.json({status:'operational',runtime:process.env.VERCEL?'vercel-serverless':'node',database:{type:'supabase',usersCount:u.count||0,requestsCount:r.count||0,persistenceType:'supabase-postgresql'},environmentChecks:{isVercel:Boolean(process.env.VERCEL),hasAppUrl:Boolean(process.env.APP_URL),hasJwtSecret:Boolean(process.env.JWT_SECRET),hasSmtpHost:Boolean(process.env.SMTP_HOST||process.env.EMAIL_HOST),hasSmtpUser:Boolean(process.env.SMTP_USER||process.env.GMAIL_USER),hasSmtpPass:Boolean(process.env.SMTP_PASS||process.env.SMTP_PASSWORD),finanzasEmailConfigured:Boolean(process.env.FINANZAS_EMAIL)}});}catch(e){res.status(503).json({status:'unavailable',database:{type:'supabase'},error:e instanceof Error?e.message:'Database unavailable'});}});
app.get(['/api/me','/me'],async(req,res)=>{try{const u=await auth(req);const allUsers=await listUsers();res.json({user:u,allUsers,appUrl:baseUrl(req),finanzasEmail:process.env.FINANZAS_EMAIL||'finanzas@dimer.com.mx',systemsEmail:'sistemas@dimer.com.mx'});}catch(e){err(res,e);}});
app.post(['/api/auth/login','/auth/login','/api/login','/login'],async(req,res)=>{try{const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');if(!email||!password)return res.status(400).json({success:false,error:'Correo electrónico y contraseña requeridos'});const u=await getUserByEmail(email);if(!u)return res.status(401).json({success:false,error:'No existe una cuenta registrada con este correo.'});if(u.status!=='ACTIVO')return res.status(403).json({success:false,error:'Esta cuenta está inactiva.'});if(!verifyPassword(password,u.passwordHash,u.salt))return res.status(401).json({success:false,error:'Contraseña incorrecta.'});const roles=await listRoles();const user=sanitizeUser(u,roles.find(r=>r.id===u.roleId));const token=jwtSign({sub:u.id,email:u.email});res.cookie('dimer_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production'||Boolean(process.env.VERCEL),sameSite:'lax',path:'/',maxAge:8*60*60*1000});await recordAuditLog({userId:u.id,action:'INICIO_SESION',details:{email:u.email,role:u.role}});res.json({success:true,user});}catch(e){err(res,e);}});
app.post('/api/auth/logout',async(req,res)=>{try{const u=await auth(req);if(u)await recordAuditLog({userId:u.id,action:'CIERRE_SESION',details:{email:u.email}});res.setHeader('Set-Cookie','dimer_session=; Max-Age=0; Path=/; HttpOnly; SameSite=Lax');res.json({success:true});}catch(e){err(res,e);}});
app.post('/api/switch-user',(_req,res)=>res.status(403).json({error:'Cambio de usuario deshabilitado en producción. Inicia sesión con credenciales reales.'}));
app.post('/api/auth/register-init',async(req,res)=>{try{const {name,email,password,department}=req.body||{};const clean=String(email||'').trim().toLowerCase();if(!name||!clean||!password)return res.status(400).json({error:'Nombre, correo y contraseña son obligatorios'});if(await getUserByEmail(clean))return res.status(400).json({error:'Ya existe una cuenta registrada con este correo.'});const dept=await getOrCreateDepartment(String(department||'General'));const {hash,salt}=hashPassword(String(password));const {code,expiresAt}=await createVerificationCode({email:clean,name:String(name),department:dept.name,roleId:'role_solicitante',passwordHash:hash,salt});const mail=await sendEmail({to:clean,subject:`Código de Verificación Dimer: ${code}`,html:buildVerificationEmailHtml({name:String(name),email:clean,code,expiresMinutes:15})});if(mail.status==='FALLIDO')return res.status(500).json({error:`Error SMTP: ${mail.error||'fallo de envío'}`});res.json({success:true,email:clean,expiresAt,simulatedCode:mail.status==='SIMULADO'?code:undefined});}catch(e){err(res,e);}});
app.post('/api/auth/verify-code',async(req,res)=>{try{const result=await verifyCodeAndActivateUser(String(req.body?.email||''),String(req.body?.code||''));if(!result.success||!result.user)return res.status(400).json({error:result.error});const roles=await listRoles();const user=sanitizeUser(result.user,roles.find(r=>r.id===result.user?.roleId));const token=jwtSign({sub:result.user.id,email:result.user.email});res.cookie('dimer_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production'||Boolean(process.env.VERCEL),sameSite:'lax',path:'/',maxAge:8*60*60*1000});await recordAuditLog({userId:result.user.id,action:'VERIFICACION_Y_ACTIVACION_CUENTA',details:{email:user.email}});try{await sendEmail({to:'sistemas@dimer.com.mx',subject:`NUEVA CUENTA REGISTRADA - ${user.name}`,html:buildNewAccountAdminEmailHtml({user,registeredAt:new Date().toISOString()})});}catch{}res.json({success:true,user,message:'Cuenta verificada y activada con éxito.'});}catch(e){err(res,e);}});
app.post('/api/auth/resend-code',async(req,res)=>{try{const clean=String(req.body?.email||'').trim().toLowerCase();const {data,error}=await supabase.from('verification_codes').select('*').eq('email',clean).maybeSingle();if(error)throw error;if(!data)return res.status(404).json({error:'No hay un registro pendiente para este correo.'});const code=crypto.randomInt(100000,1000000).toString();const expiresAt=new Date(Date.now()+15*60*1000).toISOString();const {error:updateError}=await supabase.from('verification_codes').update({code,expires_at:expiresAt,attempts:0}).eq('email',clean);if(updateError)throw updateError;const mail=await sendEmail({to:clean,subject:`Nuevo Código de Verificación Dimer: ${code}`,html:buildVerificationEmailHtml({name:data.name,email:clean,code,expiresMinutes:15})});if(mail.status==='FALLIDO')return res.status(500).json({error:mail.error||'Fallo SMTP'});res.json({success:true,expiresAt,simulatedCode:mail.status==='SIMULADO'?code:undefined});}catch(e){err(res,e);}});

// Keep the remainder of the existing API implementation below unchanged.
// This file is intentionally kept as the canonical Express application entrypoint.

app.get('/api/code-artifacts',async(_req,res)=>{try{const {NEXTJS_CODE_ARTIFACTS}=await import('./nextjsArtifacts');res.json(NEXTJS_CODE_ARTIFACTS);}catch(e){err(res,e);}});
app.all('/api/*',(_req,res)=>res.status(404).json({error:'Ruta API no encontrada'}));
app.use((e:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error('[DIMER]',e);if(!res.headersSent)res.status(500).json({success:false,error:'Error interno del servidor'});});return app;}
