import express from 'express';
import cors from 'cors';
import crypto from 'crypto';
import { generateNextFolio, getRequest, getUserByEmail, getUserById, insertRequest, listBosses, listDepartments, listRoles, listUsers, recordAuditLog, sanitizeUser, updateRequest, createDepartment, updateDepartment, createBoss, updateBoss, deleteBoss, createRole, updateRole, resolveUserRoles, getPopulatedRequests, deleteRequest, listAuditLogs, listEmailLogs, getSystemStats, createApprovalToken, validateApprovalToken, processApprovalTokenAction } from './db.js';
import { buildBossApprovalEmailHtml, buildRequesterConfirmationEmailHtml, buildSystemsApprovedEmailHtml, buildRejectionEmailHtml, sendEmail } from './mailService.js';
import type { Request, Response, NextFunction } from 'express';
import type { TravelRequest, User, Permission } from '../src/types.js';

const appVersion='1.0.0';
function parseCookies(req:Request){const raw=String(req.headers.cookie||'');return Object.fromEntries(raw.split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))];}));}
function jwtSign(payload:Record<string,unknown>){const secret=process.env.JWT_SECRET||'dev-secret-change-me';const head=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url');const body=Buffer.from(JSON.stringify(payload)).toString('base64url');const sig=crypto.createHmac('sha256',secret).update(`${head}.${body}`).digest('base64url');return `${head}.${body}.${sig}`;}
function jwtVerify(token:string){try{const secret=process.env.JWT_SECRET||'dev-secret-change-me';const p=token.split('.');if(p.length!==3)return null;const sig=crypto.createHmac('sha256',secret).update(`${p[0]}.${p[1]}`).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(p[2])))return null;const payload=JSON.parse(Buffer.from(p[1],'base64url').toString('utf8'));if(payload.exp&&payload.exp<Math.floor(Date.now()/1000))return null;return payload;}catch{return null;}}
function setSessionCookie(res:Response,req:Request,token:string){const secure=String(req.headers['x-forwarded-proto']||'').split(',')[0]==='https'||process.env.VERCEL==='1';res.cookie?.('dimer_session',token,{httpOnly:true,sameSite:'lax',secure,maxAge:1000*60*60*8,path:'/'});}
async function auth(req:Request){const cookies=parseCookies(req);const bearer=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();const token=bearer||String(cookies.dimer_session||'');if(!token)return null;const p=jwtVerify(token);if(!p?.sub)return null;const u=await getUserById(String(p.sub));if(!u||u.status!=='ACTIVO')return null;return u;}
function requireAuth(req:Request,res:Response,next:NextFunction){auth(req).then(u=>{if(!u)return res.status(401).json({error:'Autenticación requerida'});(req as any).dimerUser=u;next();}).catch(e=>res.status(500).json({error:e instanceof Error?e.message:'Error de autenticación'}));}
function hasPermission(u:User,p:Permission){return u.role==='ADMIN'||u.permissions?.includes(p)||false;}
function requirePermission(p:Permission){return (req:Request,res:Response,next:NextFunction)=>{const u=(req as any).dimerUser as User;if(!u||!hasPermission(u,p))return res.status(403).json({error:'Permiso insuficiente'});next();};}
function err(res:Response,e:unknown){return res.status(500).json({error:e instanceof Error?e.message:'Error interno'});}
function baseUrl(req:Request){if(process.env.VERCEL_PROJECT_PRODUCTION_URL)return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;if(process.env.VERCEL_URL)return `https://${process.env.VERCEL_URL}`;const configured=(process.env.PUBLIC_APP_URL||process.env.APP_URL||'').trim().replace(/\/+$/,'');if(configured&&!configured.includes('ai.studio')&&!configured.includes('aistudio.google.com')){if(!(process.env.VERCEL&&configured.includes('localhost')))return configured;}const host=String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim();const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0].trim();return host?`${proto}://${host}`:'http://localhost:3000';}

export function createApp(){
  const app=express();
  app.use(cors({origin:true,credentials:true}));
  app.use(express.json());
  app.use(express.urlencoded({extended:true}));

  app.get('/api/health',async(_req,res)=>res.json({ok:true,service:'viaticos-dimer-api',environment:process.env.VERCEL?'vercel-serverless':'node-server',version:appVersion,timestamp:new Date().toISOString()}));
  app.get('/api/me',async(req,res)=>{try{const u=await auth(req);if(!u)return res.status(401).json({error:'No autenticado'});return res.json({user:u});}catch(e){return err(res,e);}});
  app.post('/api/auth/logout',(req,res)=>{res.setHeader('Set-Cookie','dimer_session=; Max-Age=0; Path=/; HttpOnly; SameSite=Lax');res.json({success:true});});
  app.get('/api/users',requireAuth,requirePermission('administrar_usuarios'),async(_req,res)=>{try{res.json(await listUsers());}catch(e){err(res,e);}});
  app.get('/api/departments',requireAuth,async(_req,res)=>{try{res.json(await listDepartments());}catch(e){err(res,e);}});
  app.get('/api/bosses',requireAuth,requirePermission('administrar_jefes'),async(_req,res)=>{try{res.json(await listBosses());}catch(e){err(res,e);}});
  app.post('/api/bosses',requireAuth,requirePermission('administrar_jefes'),async(req,res)=>{try{res.json({success:true,boss:await createBoss(String(req.body?.name||''),String(req.body?.email||''),String(req.body?.department||''))});}catch(e){err(res,e);}});
  app.put('/api/bosses/:id',requireAuth,requirePermission('administrar_jefes'),async(req,res)=>{try{res.json({success:true,boss:await updateBoss(String(req.params.id),req.body||{})});}catch(e){err(res,e);}});
  app.delete('/api/bosses/:id',requireAuth,requirePermission('administrar_jefes'),async(req,res)=>{try{await deleteBoss(String(req.params.id));res.json({success:true});}catch(e){err(res,e);}});
  app.get('/api/roles',requireAuth,requirePermission('administrar_roles'),async(_req,res)=>{try{res.json(await listRoles());}catch(e){err(res,e);}});
  app.post('/api/roles',requireAuth,requirePermission('administrar_roles'),async(req,res)=>{try{res.json({success:true,role:await createRole(req.body||{})});}catch(e){err(res,e);}});
  app.put('/api/roles/:id',requireAuth,requirePermission('administrar_roles'),async(req,res)=>{try{res.json({success:true,role:await updateRole(String(req.params.id),req.body||{})});}catch(e){err(res,e);}});
  app.get('/api/requests',async(req,res)=>{try{const u=await auth(req);const rs=await getPopulatedRequests();if(!u)return res.json(rs);if(u.role==='ADMIN'||u.role==='FINANZAS'||u.role==='JEFE'||hasPermission(u,'ver_todas_solicitudes'))return res.json(rs);res.json(rs.filter(r=>r.userId===u.id));}catch(e){err(res,e);}});
  app.get('/api/requests/:id',requireAuth,async(req,res)=>{try{const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});const u=(req as any).dimerUser as User;if(u.role!=='ADMIN'&&u.role!=='FINANZAS'&&u.role!=='JEFE'&&r.userId!==u.id)return res.status(403).json({error:'No autorizado'});res.json(r);}catch(e){err(res,e);}});
  app.post('/api/requests',requireAuth,async(req,res)=>{try{const u=(req as any).dimerUser as User;const body=req.body||{};const id=`req_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;const folio=await generateNextFolio();const request:TravelRequest={...body,id,folio,status:'PENDIENTE_APROBACION',userId:u.id,requesterName:u.name,department:u.department,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const created=await insertRequest(request);await recordAuditLog({requestId:created.id,userId:u.id,action:'CREACION_SOLICITUD',details:{folio:created.folio,destination:created.destination,amountRequested:created.amountRequested}});if(created.approvalToken){try{const approvalUrl=`${baseUrl(req)}/api/approval/token-action?token=${encodeURIComponent(created.approvalToken)}`;await sendEmail({to:created.bossEmail,subject:`AUTORIZACIÓN DE VIÁTICOS - Folio ${created.folio}`,html:buildBossApprovalEmailHtml({request:created,user:u,approveUrl:approvalUrl,rejectUrl:approvalUrl,token:created.approvalToken}),requestId:created.id,folio:created.folio});}catch(e){console.error('Error enviando correo de aprobación:',e);}}res.json(created);}catch(e){err(res,e);}});
  app.delete('/api/requests/:id',requireAuth,async(req,res)=>{try{const u=(req as any).dimerUser as User;if(u.role!=='ADMIN')return res.status(403).json({error:'Solo el administrador puede eliminar solicitudes.'});const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});if(['APROBADA','PAGADA','FINALIZADA','CANCELADA'].includes(r.status))return res.status(400).json({error:`La solicitud ${r.folio} ya está en estado ${r.status} y no puede eliminarse.`});await deleteRequest(r.id);await recordAuditLog({requestId:r.id,userId:u.id,action:'ELIMINACION_SOLICITUD',details:{folio:r.folio,previousStatus:r.status,requesterName:r.requesterName,reason:'Eliminación administrativa de solicitud no aprobada'}});res.json({success:true,folio:r.folio});}catch(e){err(res,e);}});
  app.post('/api/requests/:id/cancel',requireAuth,async(req,res)=>{try{const u=(req as any).dimerUser as User;if(u.role!=='ADMIN')return res.status(403).json({error:'Solo el administrador puede cancelar solicitudes aprobadas.'});const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});if(r.status!=='APROBADA')return res.status(400).json({error:`Solo se pueden cancelar solicitudes APROBADAS. Estado actual: ${r.status}.`});const reason=String(req.body?.reason||'Viaje no realizado').trim()||'Viaje no realizado';const updated=await updateRequest(r.id,{status:'CANCELADA',comments:`Cancelada por administrador: ${reason}`,updatedAt:new Date().toISOString()});await recordAuditLog({requestId:r.id,userId:u.id,action:'CANCELACION_SOLICITUD_APROBADA',details:{folio:r.folio,reason,previousStatus:r.status,amountAuthorized:r.amountAuthorized}});res.json({success:true,request:updated});}catch(e){err(res,e);}});
  app.get('/api/audit-logs',requireAuth,requirePermission('ver_reportes'),async(_req,res)=>{try{res.json(await listAuditLogs());}catch(e){err(res,e);}});
  app.get('/api/outbox',requireAuth,requirePermission('ver_reportes'),async(_req,res)=>{try{res.json(await listEmailLogs());}catch(e){err(res,e);}});
  app.get('/api/stats',requireAuth,requirePermission('ver_reportes'),async(_req,res)=>{try{res.json(await getSystemStats());}catch(e){err(res,e);}});
  return app;
}
