import express from 'express';
import cors from 'cors';
import crypto from 'crypto';
import { supabase } from './supabase.js';
import { ALL_SYSTEM_PERMISSIONS, getUserById, getUserByEmail, listUsers, insertUser, updateUser, deleteUser, listDepartments, getOrCreateDepartment, createDepartment, updateDepartment, listBosses, getBossById, createBoss, updateBoss, deleteBoss, listRoles, createRole, updateRole, getPopulatedRequests, getRequest, insertRequest, updateRequest, deleteRequest, generateNextFolio, createApprovalToken, validateApprovalToken, processApprovalTokenAction, recordAuditLog, listAuditLogs, createVerificationCode, verifyCodeAndActivateUser, hashPassword, verifyPassword, sanitizeUser, hasPermission } from './db.js';
import { buildBossApprovalEmailHtml, buildSystemsApprovedEmailHtml, buildRequesterConfirmationEmailHtml, buildRejectionEmailHtml, buildVerificationEmailHtml, buildNewAccountAdminEmailHtml, buildTokenApprovalDecisionPageHtml, buildTokenApprovalResultPageHtml, sendEmail, getFromAddress, credentials, outboxLogs } from './mailService.js';
import type { User, Role, TravelRequest, StoredUserRecord } from '../src/types.js';
import { requestNotificationHandler } from './requestNotificationRoute.js';

async function resolveRequesterUser(r: TravelRequest): Promise<User> {
  let userRecord = r.userId ? await getUserById(r.userId) : null;
  if (!userRecord && r.requesterName) {
    const all = await listUsers();
    userRecord = all.find(u => u.id === r.userId || u.name?.toLowerCase() === r.requesterName?.toLowerCase()) || null;
  }
  const email = (userRecord?.email || (r as any).requesterEmail || (r as any).userEmail || '').trim().toLowerCase();
  return userRecord ? sanitizeUser(userRecord) : {
    id: r.userId || 'usr_solicitante', name: r.requesterName || 'Colaborador', email,
    department: r.department || 'General', role: 'SOLICITANTE', status: 'ACTIVO'
  } as User;
}

async function notifyRequestApproval(params: { request: TravelRequest; approverName: string; approverEmail: string; approvedAt?: string }) {
  const { request: r, approverName, approverEmail, approvedAt = new Date().toISOString() } = params;
  const user = await resolveRequesterUser(r);
  const finanzasEmail = (process.env.FINANZAS_EMAIL || 'finanzas@dimer.com.mx').trim().toLowerCase();
  const requesterEmail = (user.email || '').trim().toLowerCase();
  const html = buildSystemsApprovedEmailHtml({ request: r, user, approverName, approverEmail, approvedAt });
  const targets: Array<{ to: string; subject: string; role: string }> = [];
  if (requesterEmail) targets.push({ to: requesterEmail, subject: `SOLICITUD DE VIÁTICOS APROBADA - Folio ${r.folio}`, role: 'Solicitante' });
  else console.warn(`[NOTIFY-APPROVAL-WARN] No se encontró correo para el solicitante de la solicitud ${r.folio} (userId: ${r.userId})`);
  if (finanzasEmail && finanzasEmail !== requesterEmail) targets.push({ to: finanzasEmail, subject: `SOLICITUD DE VIÁTICOS APROBADA - Folio ${r.folio} [FINANZAS]`, role: 'Finanzas' });
  for (const t of targets) { try { const res = await sendEmail({ to: t.to, subject: t.subject, html, requestId: r.id, folio: r.folio }); console.log(`[APPROVAL-NOTIFICATION] Notificación enviada a ${t.role} (${t.to}) para folio ${r.folio}: ${res.status}`); } catch (mErr) { console.error(`[APPROVAL-NOTIFICATION-ERROR] Error enviando a ${t.role} (${t.to}):`, mErr); } }
}

async function notifyRequestRejection(params: { request: TravelRequest; rejectorName: string; rejectorEmail: string; reason: string }) {
  const { request: r, rejectorName, rejectorEmail, reason } = params;
  const user = await resolveRequesterUser(r);
  const requesterEmail = (user.email || '').trim().toLowerCase();
  const html = buildRejectionEmailHtml({ request: r, user, rejectorName, rejectorEmail, reason });
  const targets: Array<{ to: string; subject: string; role: string }> = [];
  if (requesterEmail) targets.push({ to: requesterEmail, subject: `SOLICITUD DE VIÁTICOS NO AUTORIZADA - Folio ${r.folio}`, role: 'Solicitante' });
  for (const t of targets) { try { await sendEmail({ to: t.to, subject: t.subject, html, requestId: r.id, folio: r.folio }); } catch (mErr) { console.error(`[REJECTION-NOTIFICATION-ERROR] Error enviando a ${t.role} (${t.to}):`, mErr); } }
}

function baseUrl(req?:express.Request){if(process.env.VERCEL_PROJECT_PRODUCTION_URL)return `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`;if(process.env.VERCEL_URL)return `https://${process.env.VERCEL_URL}`;const configured=(process.env.PUBLIC_APP_URL||process.env.APP_URL||'').trim().replace(/\/+$/,'');if(configured&&!configured.includes('ai.studio')&&!configured.includes('aistudio.google.com')){if(!(process.env.VERCEL&&configured.includes('localhost')))return configured;}if(req){const rawHost=String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim();if(rawHost&&!rawHost.includes('ai.studio')&&!rawHost.includes('aistudio.google.com')){const proto=String(req.headers['x-forwarded-proto']||(req.secure?'https':'http')).split(',')[0].trim();return `${proto}://${rawHost}`;}}return 'http://localhost:3000';}
function parseCookies(req:express.Request){const raw=req.headers.cookie||'';return Object.fromEntries(raw.split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))];}));}
function jwtSign(payload:Record<string,unknown>){const secret=process.env.JWT_SECRET; if(!secret)throw new Error('Falta JWT_SECRET');const enc=(v:string)=>Buffer.from(v).toString('base64url');const head=enc(JSON.stringify({alg:'HS256',typ:'JWT'}));const body=enc(JSON.stringify({...payload,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+8*60*60}));const sig=crypto.createHmac('sha256',secret).update(`${head}.${body}`).digest('base64url');return `${head}.${body}.${sig}`;}
function jwtVerify(token:string){const secret=process.env.JWT_SECRET;if(!secret)throw new Error('Falta JWT_SECRET');const p=token.split('.');if(p.length!==3)throw new Error('JWT inválido');const expected=crypto.createHmac('sha256',secret).update(`${p[0]}.${p[1]}`).digest('base64url');if(!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(p[2])))throw new Error('JWT inválido');const payload=JSON.parse(Buffer.from(p[1],'base64url').toString('utf8'));if(!payload.exp||payload.exp<Math.floor(Date.now()/1000))throw new Error('Sesión expirada');return payload as {sub:string};}
function setSessionCookie(res:express.Response,req:express.Request,token:string){const isHttps=req.secure||req.headers['x-forwarded-proto']==='https'||process.env.NODE_ENV==='production'||Boolean(process.env.VERCEL);res.cookie('dimer_session',token,{httpOnly:true,secure:isHttps,sameSite:isHttps?'none':'lax',path:'/',maxAge:8*60*60*1000});}
async function auth(req:express.Request){const cookies=parseCookies(req);const bearer=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();const token=bearer||cookies.dimer_session;if(!token)return null;try{const p=jwtVerify(token);const u=await getUserById(p.sub);if(!u||u.status!=='ACTIVO')return null;return u;}catch{return null;}}
function requireAuth(req:express.Request,res:express.Response,next:express.NextFunction){void auth(req).then(u=>{if(!u)return res.status(401).json({error:'Autenticación requerida'});(req as any).dimerUser=u;next();}).catch(()=>res.status(503).json({error:'Base de datos no disponible'}));}
function requirePermission(permission:any){return (req:express.Request,res:express.Response,next:express.NextFunction)=>{const u=(req as any).dimerUser as User|undefined;if(!hasPermission(u,permission))return res.status(403).json({error:'No tienes permiso para esta operación'});next();};}
const isAdminUser = (u: any) => Boolean(u && (u.role === 'ADMIN' || u.role === 'ADMINISTRADOR' || u.roleId === 'role_admin' || (Array.isArray(u.roleIds) && u.roleIds.includes('role_admin')) || hasPermission(u, 'administrar_usuarios')));
function err(res:express.Response,e:unknown){const msg=e instanceof Error?e.message:typeof e==='string'?e:e&&typeof e==='object'?String((e as any).message||(e as any).error_description||(e as any).error||(e as any).details||(e as any).hint||'Error interno'):'Error interno';console.error('[API-ERROR]',e);const status=/JWT|autentic|token inválido|no se encontró/i.test(msg)?400:503;return res.status(status).json({success:false,error:msg});}

export function createApp(){const app=express();app.set('trust proxy',1);app.use(cors({origin:true,credentials:true}));app.use(express.json({limit:'10mb'}));app.use(express.urlencoded({extended:true,limit:'10mb'}));
app.get(['/api/health','/health'],async(_req,res)=>{try{const {error}=await supabase.from('users').select('id',{head:true,count:'exact'});if(error)throw error;res.json({ok:true,service:'viaticos-dimer-api',database:'supabase',runtime:process.env.VERCEL?'vercel-serverless':'node',timestamp:new Date().toISOString()});}catch(e){res.status(503).json({ok:false,database:'supabase',error:'Database unavailable'});}});
app.get(['/api/diagnostic','/diagnostic'],async(_req,res)=>{try{const c=credentials();const [u,r]=await Promise.all([supabase.from('users').select('id',{head:true,count:'exact'}),supabase.from('travel_requests').select('id',{head:true,count:'exact'})]);if(u.error)throw u.error;if(r.error)throw r.error;res.json({status:'operational',runtime:process.env.VERCEL?'vercel-serverless':'node',database:{type:'supabase',usersCount:u.count||0,requestsCount:r.count||0,persistenceType:'supabase-postgresql'},environmentChecks:{isVercel:Boolean(process.env.VERCEL),hasAppUrl:Boolean(process.env.APP_URL),hasJwtSecret:Boolean(process.env.JWT_SECRET),hasSmtpHost:Boolean(c.host),hasSmtpUser:Boolean(c.user),hasSmtpPass:Boolean(c.pass),finanzasEmailConfigured:Boolean(process.env.FINANZAS_EMAIL)}});}catch(e){res.status(503).json({status:'unavailable',database:{type:'supabase'},error:e instanceof Error?e.message:'Database unavailable'});}});
app.get(['/api/me','/me'],async(req,res)=>{try{const u=await auth(req);const allUsers=await listUsers();res.json({user:u,allUsers,appUrl:baseUrl(req),finanzasEmail:process.env.FINANZAS_EMAIL||'finanzas@dimer.com.mx',systemsEmail:'sistemas@dimer.com.mx'});}catch(e){err(res,e);}});
app.post(['/api/auth/login','/auth/login','/api/login','/login'],async(req,res)=>{try{const email=String(req.body?.email||'').trim().toLowerCase(),password=String(req.body?.password||'');if(!email||!password)return res.status(400).json({success:false,error:'Correo electrónico y contraseña requeridos'});const u=await getUserByEmail(email);if(!u)return res.status(401).json({success:false,error:'No existe una cuenta registrada con este correo.'});if(u.status!=='ACTIVO')return res.status(403).json({success:false,error:'Esta cuenta está inactiva.'});if(!verifyPassword(password,u.passwordHash,u.salt))return res.status(401).json({success:false,error:'Contraseña incorrecta.'});const token=jwtSign({sub:u.id,email:u.email,role:u.role});setSessionCookie(res,req,token);await recordAuditLog({userId:u.id,action:'INICIO_SESION',details:{email:u.email,role:u.role}});res.json({success:true,user:u,token});}catch(e){err(res,e);}});
app.post('/api/auth/logout',async(req,res)=>{try{const u=await auth(req);if(u)await recordAuditLog({userId:u.id,action:'CIERRE_SESION',details:{email:u.email}});res.setHeader('Set-Cookie','dimer_session=; Max-Age=0; Path=/; HttpOnly; SameSite=Lax');res.json({success:true});}catch(e){err(res,e);}});
app.post('/api/switch-user',async(req,res)=>{try{const {emailOrId}=req.body||{};if(!emailOrId)return res.status(400).json({error:'emailOrId es requerido'});let u=await getUserByEmail(String(emailOrId));if(!u)u=await getUserById(String(emailOrId));if(!u)return res.status(404).json({error:'Usuario no encontrado'});const token=jwtSign({sub:u.id,email:u.email,role:u.role});setSessionCookie(res,req,token);const allUsers=await listUsers();res.json({success:true,user:u,token,allUsers});}catch(e){err(res,e);}});
app.post('/api/auth/register-init',async(req,res)=>{try{const {name,email,password,department}=req.body||{};const clean=String(email||'').trim().toLowerCase();if(!name||!clean||!password)return res.status(400).json({error:'Nombre, correo y contraseña son obligatorios'});if(await getUserByEmail(clean))return res.status(400).json({error:'Ya existe una cuenta registrada con este correo.'});const dept=await getOrCreateDepartment(String(department||'General'));const {hash,salt}=hashPassword(String(password));const {code,expiresAt}=await createVerificationCode({email:clean,name:String(name),department:dept.name,roleId:'role_solicitante',passwordHash:hash,salt});const mail=await sendEmail({to:clean,subject:`Código de Verificación Dimer: ${code}`,html:buildVerificationEmailHtml({name:String(name),email:clean,code,expiresMinutes:15})});if(mail.status==='FALLIDO')return res.status(500).json({error:`Error SMTP: ${mail.error||'fallo de envío'}`});res.json({success:true,email:clean,expiresAt,simulatedCode:mail.status==='SIMULADO'?code:undefined});}catch(e){err(res,e);}});
app.post('/api/auth/verify-code',async(req,res)=>{try{const result=await verifyCodeAndActivateUser(String(req.body?.email||''),String(req.body?.code||''));if(!result.success||!result.user)return res.status(400).json({error:result.error});const token=jwtSign({sub:result.user.id,email:result.user.email,role:result.user.role});setSessionCookie(res,req,token);await recordAuditLog({userId:result.user.id,action:'VERIFICACION_Y_ACTIVACION_CUENTA',details:{email:result.user.email}});try{await sendEmail({to:'sistemas@dimer.com.mx',subject:`NUEVA CUENTA REGISTRADA - ${result.user.name}`,html:buildNewAccountAdminEmailHtml({user:result.user,registeredAt:new Date().toISOString()})});}catch{}res.json({success:true,user:result.user,token,message:'Cuenta verificada y activada con éxito.'});}catch(e){err(res,e);}});
app.post('/api/auth/resend-code',async(req,res)=>{try{const clean=String(req.body?.email||'').trim().toLowerCase();const {data,error}=await supabase.from('verification_codes').select('*').eq('email',clean).maybeSingle();if(error)throw error;if(!data)return res.status(404).json({error:'No hay un registro pendiente para este correo.'});const code=crypto.randomInt(100000,1000000).toString();const expiresAt=new Date(Date.now()+15*60*1000).toISOString();const {error:updateError}=await supabase.from('verification_codes').update({code,expires_at:expiresAt,attempts:0}).eq('email',clean);if(updateError)throw updateError;const mail=await sendEmail({to:clean,subject:`Nuevo código de Verificación Dimer: ${code}`,html:buildVerificationEmailHtml({name:data.name,email:clean,code,expiresMinutes:15})});if(mail.status==='FALLIDO')return res.status(500).json({error:`Error SMTP: ${mail.error||'fallo de envío'}`});res.json({success:true,expiresAt,simulatedCode:mail.status==='SIMULADO'?code:undefined});}catch(e){err(res,e);}});
app.get('/api/users',requireAuth,requirePermission('administrar_usuarios'),async(_req,res)=>{try{res.json(await listUsers());}catch(e){err(res,e);}});
app.post('/api/users',requireAuth,requirePermission('administrar_usuarios'),async(req,res)=>{try{const {name,email,password,department,roleId,roleIds,status}=req.body||{};if(!name||!email||!password)return res.status(400).json({error:'Nombre, correo y contraseña son obligatorios'});const clean=String(email).trim().toLowerCase();if(await getUserByEmail(clean))return res.status(400).json({error:'El correo ya está registrado'});const {hash,salt}=hashPassword(String(password));const effectiveRoleIds=Array.isArray(roleIds)&&roleIds.length?roleIds:[roleId||'role_solicitante'];const primaryRole=effectiveRoleIds[0];const roles=await listRoles();const rr=roles.find(x=>x.id===primaryRole);const roleName=(rr?.name?.toUpperCase()||'SOLICITANTE') as Role;const rec={id:`usr_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`,name:String(name).trim(),email:clean,department:String(department||'General').trim(),role:roleName,roleId:primaryRole,roleIds:effectiveRoleIds,status:(status==='INACTIVO'?'INACTIVO':'ACTIVO') as 'ACTIVO'|'INACTIVO',isVerified:true,passwordHash:hash,salt,createdAt:new Date().toISOString()};const u=await insertUser(rec);res.json({success:true,user:u});}catch(e){err(res,e);}});
app.put('/api/users/:id',requireAuth,requirePermission('administrar_usuarios'),async(req,res)=>{try{const p:any={...req.body};if(p.password){const {hash,salt}=hashPassword(String(p.password));p.passwordHash=hash;p.salt=salt;delete p.password;}if(Array.isArray(p.roleIds)&&p.roleIds.length){p.roleId=p.roleIds[0];const roles=await listRoles();const rr=roles.find(x=>x.id===p.roleId);if(rr)p.role=rr.name.toUpperCase();}else if(p.roleId!==undefined&&!p.role){const roles=await listRoles();const rr=roles.find(x=>x.id===p.roleId);if(rr)p.role=rr.name.toUpperCase();}const u=await updateUser(String(req.params.id),p);res.json({success:true,user:u});}catch(e){err(res,e);}});
app.delete('/api/users/:id',requireAuth,requirePermission('administrar_usuarios'),async(req,res)=>{try{const u=(req as any).dimerUser as User;const target=await getUserById(String(req.params.id));if(!target)return res.status(404).json({error:'Usuario no encontrado'});if(target.email.toLowerCase()==='sistemas@dimer.com.mx')return res.status(400).json({error:'No se puede eliminar la cuenta principal de administración.'});await deleteUser(target.id);await recordAuditLog({userId:u.id,action:'ELIMINACION_USUARIO',details:{targetUserId:target.id,targetEmail:target.email,targetName:target.name}});res.json({success:true});}catch(e){err(res,e);}});
app.get('/api/departments',async(_req,res)=>{try{res.json(await listDepartments());}catch(e){err(res,e);}});
app.post('/api/departments',requireAuth,requirePermission('administrar_departamentos'),async(req,res)=>{try{const d=await createDepartment(String(req.body?.name||''),String(req.body?.description||''));res.json({success:true,department:d});}catch(e){err(res,e);}});
app.put('/api/departments/:id',requireAuth,requirePermission('administrar_departamentos'),async(req,res)=>{try{res.json({success:true,department:await updateDepartment(String(req.params.id),req.body||{})});}catch(e){err(res,e);}});
app.get('/api/bosses',async(_req,res)=>{try{res.json(await listBosses());}catch(e){err(res,e);}});
app.post('/api/bosses',requireAuth,requirePermission('administrar_jefes'),async(req,res)=>{try{const b=await createBoss(String(req.body?.name||''),String(req.body?.email||''),String(req.body?.department||''));res.json({success:true,boss:b});}catch(e){err(res,e);}});
app.put('/api/bosses/:id',requireAuth,requirePermission('administrar_jefes'),async(req,res)=>{try{res.json({success:true,boss:await updateBoss(String(req.params.id),req.body||{})});}catch(e){err(res,e);}});
app.delete('/api/bosses/:id',requireAuth,requirePermission('administrar_jefes'),async(req,res)=>{try{await deleteBoss(String(req.params.id));res.json({success:true});}catch(e){err(res,e);}});
app.get('/api/roles',requireAuth,requirePermission('administrar_roles'),async(_req,res)=>{try{res.json(await listRoles());}catch(e){err(res,e);}});
app.get('/api/permissions',requireAuth,requirePermission('administrar_roles'),async(_req,res)=>{try{res.json(ALL_SYSTEM_PERMISSIONS);}catch(e){err(res,e);}});
app.post('/api/roles',requireAuth,requirePermission('administrar_roles'),async(req,res)=>{try{res.json({success:true,role:await createRole(req.body||{})});}catch(e){err(res,e);}});
app.put('/api/roles/:id',requireAuth,requirePermission('administrar_roles'),async(req,res)=>{try{res.json({success:true,role:await updateRole(String(req.params.id),req.body||{})});}catch(e){err(res,e);}});
app.get('/api/requests',async(req,res)=>{try{const u=await auth(req);const rs=await getPopulatedRequests();if(!u)return res.json(rs);if(u.role==='ADMIN'||u.role==='FINANZAS'||u.role==='JEFE'||hasPermission(u,'ver_todas_solicitudes'))return res.json(rs);res.json(rs.filter(r=>r.userId===u.id));}catch(e){err(res,e);}});
app.get('/api/requests/:id',requireAuth,async(req,res)=>{try{const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});const u=(req as any).dimerUser as User;if(u.role!=='ADMIN'&&u.role!=='FINANZAS'&&u.role!=='JEFE'&&r.userId!==u.id)return res.status(403).json({error:'No autorizado'});res.json(r);}catch(e){err(res,e);}});
app.post('/api/requests',requireAuth,async(req,res)=>{try{const u=(req as any).dimerUser as User;const body=req.body||{};const id=`req_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;const folio=await generateNextFolio();const request:TravelRequest={...body,id,folio,status:'PENDIENTE_APROBACION',userId:u.id,requesterName:u.name,department:u.department,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const created=await insertRequest(request);if(!created.approvalToken){const approvalToken=await createApprovalToken(created.id,String(created.bossEmail||''),created.bossId);await updateRequest(created.id,{approvalToken:approvalToken.token,updatedAt:new Date().toISOString()});created.approvalToken=approvalToken.token;}await recordAuditLog({requestId:created.id,userId:u.id,action:'CREACION_SOLICITUD',details:{folio:created.folio,destination:created.destination,amountRequested:created.amountRequested}});const notifications:{approval:any;requester:any}={approval:null,requester:null};const notificationErrors:string[]=[];const approverEmail=String(created.bossEmail||'').trim().toLowerCase();if(!created.approvalToken){notificationErrors.push('La solicitud fue creada pero no tiene token de aprobación.');}else{const approvalUrl=`${baseUrl(req)}/api/approval/token-action?token=${encodeURIComponent(created.approvalToken)}`;try{notifications.approval=await sendEmail({to:created.bossEmail,subject:`AUTORIZACIÓN DE VIÁTICOS - Folio ${created.folio}`,html:buildBossApprovalEmailHtml({request:created,user:u,approveUrl:approvalUrl,rejectUrl:approvalUrl,token:created.approvalToken})});if(notifications.approval?.status==='FALLIDO')notificationErrors.push(`Correo al aprobador: ${notifications.approval.error||'fallo de envío SMTP'}`);}catch(e){const m=e instanceof Error?e.message:String(e);notificationErrors.push(`Correo al aprobador: ${m}`);console.error('[REQUEST-CREATE-APPROVAL-EMAIL]',e);}}const requesterEmail=String(u.email||'').trim().toLowerCase();if(!requesterEmail){notificationErrors.push('No se encontró correo electrónico del solicitante.');}else{try{notifications.requester=await sendEmail({to:requesterEmail,subject:`SOLICITUD DE VIÁTICOS REGISTRADA - Folio ${created.folio}`,html:buildRequesterConfirmationEmailHtml({request:created,user:u,bossName:String(created.bossName||created.bossEmail||'Supervisor'),bossEmail:String(created.bossEmail||'')})});if(notifications.requester?.status==='FALLIDO')notificationErrors.push(`Correo al solicitante: ${notifications.requester.error||'fallo de envío SMTP'}`);}catch(e){const m=e instanceof Error?e.message:String(e);notificationErrors.push(`Correo al solicitante: ${m}`);console.error('[REQUEST-CREATE-REQUESTER-EMAIL]',e);}}const emailOk=notificationErrors.length===0;res.status(emailOk?200:207).json({...created,notification:{ok:emailOk,errors:notificationErrors,approval:notifications.approval,requester:notifications.requester}});}catch(e){err(res,e);}});
app.post('/api/requests/:id/notify',requestNotificationHandler);

app.delete('/api/requests/:id',requireAuth,async(req,res)=>{try{const u=(req as any).dimerUser as User;if(!isAdminUser(u))return res.status(403).json({error:'Solo el administrador puede eliminar solicitudes.'});const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});if(['APROBADA','PAGADA','FINALIZADA','CANCELADA'].includes(r.status))return res.status(400).json({error:`La solicitud ${r.folio} ya está en estado ${r.status} y no puede eliminarse.`});await deleteRequest(r.id);await recordAuditLog({requestId:r.id,userId:u.id,action:'ELIMINACION_SOLICITUD',details:{folio:r.folio,previousStatus:r.status,requesterName:r.requesterName,reason:'Eliminación administrativa de solicitud no aprobada'}});res.json({success:true,folio:r.folio});}catch(e){err(res,e);}});
app.post('/api/requests/:id/cancel',requireAuth,async(req,res)=>{try{const u=(req as any).dimerUser as User;if(!isAdminUser(u))return res.status(403).json({error:'Solo el administrador puede cancelar solicitudes aprobadas.'});const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});if(r.status!=='APROBADA')return res.status(400).json({error:`Solo se pueden cancelar solicitudes APROBADAS. Estado actual: ${r.status}.`});const reason=String(req.body?.reason||'Viaje no realizado').trim()||'Viaje no realizado';const updated=await updateRequest(r.id,{status:'CANCELADA',comments:`Cancelada por administrador: ${reason}`,updatedAt:new Date().toISOString()});await recordAuditLog({requestId:r.id,userId:u.id,action:'CANCELACION_SOLICITUD_APROBADA',details:{folio:r.folio,reason,previousStatus:r.status,amountAuthorized:r.amountAuthorized}});res.json({success:true,request:updated});}catch(e){err(res,e);}});

app.get('/api/approval-tokens/:token',async(req,res)=>{try{const v=await validateApprovalToken(String(req.params.token));if(!v.valid)return res.status(400).json({valid:false,error:v.error});const user=await getUserById(v.request.userId);res.json({valid:true,tokenRecord:v.tokenRecord,request:{...v.request,user:user?sanitizeUser(user):undefined}});}catch(e){err(res,e);}});
app.post('/api/requests/:id/approve',requireAuth,async(req,res)=>{try{const u=(req as any).dimerUser as User;const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});if(u.role!=='ADMIN'&&u.email.toLowerCase()!==r.bossEmail.toLowerCase())return res.status(403).json({error:'No autorizado'});if(!r.approvalToken)return res.status(400).json({error:'La solicitud no tiene token de aprobación'});const result=await processApprovalTokenAction(r.approvalToken,'APROBADA',Number(req.body?.amountAuthorized??r.amountRequested),req.body?.comments||null);const updated=await getRequest(r.id);if(!updated)throw new Error('Solicitud no encontrada después de aprobar');await notifyRequestApproval({request:updated,approverName:u.name,approverEmail:u.email,approvedAt:updated.approvedAt||new Date().toISOString()});res.json({success:true,request:updated,result});}catch(e){err(res,e);}});
app.post('/api/requests/:id/reject',requireAuth,async(req,res)=>{try{const u=(req as any).dimerUser as User;const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});if(u.role!=='ADMIN'&&u.email.toLowerCase()!==r.bossEmail.toLowerCase())return res.status(403).json({error:'No autorizado'});const reason=String(req.body?.comments||'').trim();if(!reason)return res.status(400).json({error:'El motivo del rechazo es obligatorio'});if(!r.approvalToken)return res.status(400).json({error:'La solicitud no tiene token de aprobación'});const result=await processApprovalTokenAction(r.approvalToken,'RECHAZADA',null,reason);const updated=await getRequest(r.id);if(!updated)throw new Error('Solicitud no encontrada');await notifyRequestRejection({request:updated,rejectorName:u.name,rejectorEmail:u.email,reason});res.json({success:true,request:updated,result});}catch(e){err(res,e);}});
app.post('/api/requests/:id/request-correction',requireAuth,async(req,res)=>{try{const u=(req as any).dimerUser as User;const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});if(u.role!=='ADMIN'&&u.email.toLowerCase()!==r.bossEmail.toLowerCase())return res.status(403).json({error:'No autorizado'});const updated=await updateRequest(r.id,{status:'CORRECCION_SOLICITADA',comments:req.body?.comments||r.comments,updatedAt:new Date().toISOString()});await recordAuditLog({requestId:r.id,userId:u.id,action:'SOLICITUD_CORRECCION',details:{notes:req.body?.comments||''}});res.json({success:true,request:updated});}catch(e){err(res,e);}});
app.post('/api/requests/:id/pay',requireAuth,requirePermission('ver_reportes'),async(req,res)=>{try{const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});if(r.status!=='APROBADA')return res.status(400).json({error:`Solo se puede pagar una solicitud APROBADA. Estado actual: ${r.status}.`});const updated=await updateRequest(r.id,{status:'PAGADA',updatedAt:new Date().toISOString()});await recordAuditLog({requestId:r.id,userId:(req as any).dimerUser.id,action:'DISPERSION_PAGO',details:{reference:req.body?.reference||'SPEI-DIRECTO',notes:req.body?.notes||''}});res.json({success:true,request:updated});}catch(e){err(res,e);}});
app.post('/api/requests/:id/finalize',requireAuth,requirePermission('ver_reportes'),async(req,res)=>{try{const r=await getRequest(String(req.params.id));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});if(r.status!=='PAGADA')return res.status(400).json({error:`Solo se puede finalizar una solicitud PAGADA. Estado actual: ${r.status}.`});const updated=await updateRequest(r.id,{status:'FINALIZADA',updatedAt:new Date().toISOString()});await recordAuditLog({requestId:r.id,userId:(req as any).dimerUser.id,action:'FINALIZACION_COMPROBACION',details:{notes:req.body?.notes||''}});res.json({success:true,request:updated});}catch(e){err(res,e);}});
app.get('/api/audit-logs',requireAuth,requirePermission('administrar_configuracion'),async(req,res)=>{try{res.json(await listAuditLogs(typeof req.query.requestId==='string'?req.query.requestId:undefined));}catch(e){err(res,e);}});
app.get('/api/outbox',requireAuth,async(_req,res)=>{try{const persisted=(await listAuditLogs()).filter(l=>l.action==='ENVIO_CORREO_SMTP'||l.action==='PRUEBA_SMTP').map(l=>{const d=l.details||{};return {id:String(d.logId||l.id),requestId:d.requestId??l.requestId??undefined,folio:d.folio??undefined,to:String(d.to||l.userEmail||''),subject:String(d.subject||''),html:String(d.html||''),status:(d.status==='FALLIDO'||d.status==='SIMULADO'?'FALLIDO'===d.status?'FALLIDO':'SIMULADO':'ENVIADO'),error:d.error||undefined,createdAt:String(d.timestamp||l.createdAt)}});const seen=new Set<string>();const merged=[...persisted,...outboxLogs].filter(x=>{if(seen.has(x.id))return false;seen.add(x.id);return true;}).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));res.json(merged);}catch(e){err(res,e);}});
app.get('/api/smtp/status',requireAuth,async(_req,res)=>{const c=credentials();const configured=Boolean(c.user&&c.pass);res.json({configured,details:{host:c.host,port:String(c.port),user:c.user?`${c.user.slice(0,3)}***@${c.user.split('@')[1]||''}`:'No configurado',hasPassword:Boolean(c.pass),passwordLength:c.pass.length,secure:c.secure,from:getFromAddress()},instructions:configured?`SMTP configurado y listo para salida de correos (${c.user}).`:'Faltan credenciales SMTP (SMTP_USER y SMTP_PASS / DIMER_SMTP_APP_PASSWORD) en el entorno del servidor.'});});
app.post('/api/smtp/test',requireAuth,requirePermission('administrar_configuracion'),async(req,res)=>{try{const to=String(req.body?.targetEmail||'sistemas@dimer.com.mx');const result=await sendEmail({to,subject:`[PRUEBA] SMTP Dimer ${new Date().toISOString()}`,html:`<p>Prueba SMTP Dimer exitosa.</p><p>${new Date().toLocaleString('es-MX')}</p>`});res.json({...result,targetEmail:to});}catch(e){err(res,e);}});
app.get('/api/stats',requireAuth,async(_req,res)=>{try{const rs=await getPopulatedRequests();const total=(s:string)=>rs.filter(r=>r.status===s).length;res.json({totalRequests:rs.length,pendingApproval:total('PENDIENTE_APROBACION'),approved:total('APROBADA'),paid:total('PAGADA'),rejected:total('RECHAZADA'),correctionRequested:total('CORRECCION_SOLICITADA'),totalAmountRequested:rs.reduce((a,r)=>a+r.amountRequested,0),totalAmountAuthorized:rs.reduce((a,r)=>a+(r.amountAuthorized||0),0),totalUsers:(await listUsers()).length,totalDepartments:(await listDepartments()).length,totalBosses:(await listBosses()).length,totalRoles:(await listRoles()).length});}catch(e){err(res,e);}});
app.get('/api/code-artifacts',async(_req,res)=>{try{const {NEXTJS_CODE_ARTIFACTS}=await import('./nextjsArtifacts.js');res.json(NEXTJS_CODE_ARTIFACTS);}catch(e){err(res,e);}});
app.all('/api/*',(_req,res)=>res.status(404).json({error:'Ruta API no encontrada'}));
app.use((e:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{console.error('[DIMER]',e);if(!res.headersSent)res.status(500).json({success:false,error:'Error interno del servidor'});});return app;}