import crypto from 'crypto';
import { supabase } from './supabase';
import type { User, TravelRequest, AuditLog, Role, RoleDefinition, Department, Boss, ApprovalToken, Permission } from '../src/types';

export interface StoredUserRecord extends User { passwordHash?: string; salt?: string; }
export interface PendingVerification { email:string; code:string; name:string; department:string; roleId:string; passwordHash:string; salt:string; expiresAt:number; attempts:number; }

export const ALL_SYSTEM_PERMISSIONS: {id:Permission;label:string;description:string;category:string}[] = [
['ver_solicitudes','Ver mis solicitudes','Consultar solicitudes de viáticos creadas por el usuario','Viáticos'],['crear_solicitudes','Crear solicitudes','Generar nuevos folios de viáticos y enviarlos a autorización','Viáticos'],['editar_solicitudes','Editar solicitudes','Modificar solicitudes en borrador o corrección','Viáticos'],['cancelar_solicitudes','Cancelar solicitudes','Cancelar folios propios antes de que sean dispersados','Viáticos'],['aprobar_solicitudes','Aprobar solicitudes','Dictaminar, ajustar montos y autorizar viáticos como jefe','Aprobaciones'],['ver_todas_solicitudes','Ver todas las solicitudes','Consultar el catálogo global de solicitudes corporativas','Aprobaciones'],['administrar_usuarios','Administrar usuarios','Crear, editar, activar/desactivar y resetear contraseñas','Administración'],['administrar_departamentos','Administrar departamentos','Crear y configurar el catálogo de departamentos','Administración'],['administrar_jefes','Administrar jefes','Administrar el catálogo de responsables de aprobación','Administración'],['administrar_roles','Administrar roles','Crear roles y configurar permisos granulares','Administración'],['ver_reportes','Ver reportes y Finanzas','Acceder al módulo de tesorería, pólizas y dispersión SPEI','Finanzas'],['administrar_configuracion','Administrar configuración','Bitácora inmutable, outbox SMTP y esquemas de sistema','Administración']
].map(([id,label,description,category])=>({id:id as Permission,label,description,category}));

const adminPerms: Permission[] = ALL_SYSTEM_PERMISSIONS.map(p=>p.id);
export const ROLES: RoleDefinition[] = [
{id:'role_admin',name:'Administrador',description:'Acceso total al sistema, gestión de usuarios, roles, departamentos y auditoría.',active:true,isSystem:true,permissions:adminPerms},
{id:'role_solicitante',name:'Solicitante',description:'Puede crear nuevas solicitudes y consultar exclusivamente sus propias solicitudes y su estatus.',active:true,isSystem:true,permissions:['ver_solicitudes','crear_solicitudes','editar_solicitudes','cancelar_solicitudes']},
{id:'role_solo_lectura',name:'Solo Lectura de Aprobadas',description:'Acceso de consulta exclusivo para visualizar solicitudes que ya fueron aprobadas en la empresa.',active:true,isSystem:true,permissions:['ver_solicitudes','ver_todas_solicitudes']},
{id:'role_jefe',name:'Jefe / Aprobador',description:'Autorización y dictamen de solicitudes de colaboradores a su cargo.',active:true,isSystem:true,permissions:['ver_solicitudes','crear_solicitudes','editar_solicitudes','aprobar_solicitudes','ver_todas_solicitudes']},
{id:'role_finanzas',name:'Finanzas / Tesorería',description:'Revisión de solicitudes aprobadas, dispersión de transferencias SPEI y emisión de pólizas.',active:true,isSystem:true,permissions:['ver_solicitudes','ver_todas_solicitudes','ver_reportes']}
];

export const DEPARTMENTS: Department[] = [
['dept_sistemas','Sistemas','Tecnología, Infraestructura y Soporte TI'],['dept_finanzas','Finanzas','Tesorería, Contabilidad y Pólizas'],['dept_rh','Recursos Humanos','Gestión de Talento y Desarrollo Organizacional'],['dept_produccion','Producción','Manufactura, Operaciones y Planta'],['dept_compras','Compras','Adquisiciones y Proveedores'],['dept_ventas','Ventas','Comercialización, Proyectos y Cuentas Clave'],['dept_1787749938924_826','General','Departamento registrado automáticamente']
].map(([id,name,description])=>({id,name,description,active:true,createdAt:id==='dept_1787749938924_826'?'2026-08-26T13:12:18.924Z':'2026-01-01T00:00:00.000Z'}));
export const BOSSES: Boss[]=[{id:'boss_sistemas',name:'Ing. Roberto Flores / Autorizaciones TI',email:'sistemas@dimer.com.mx',department:'Sistemas',active:true,createdAt:'2026-01-01T00:00:00.000Z'}];

export const USERS: StoredUserRecord[] = [
{id:'usr_adm_1',name:'Ing. Sistemas Admin',email:'sistemas@dimer.com.mx',role:'ADMIN',roleId:'role_admin',department:'Sistemas',status:'ACTIVO',isVerified:true,passwordHash:'6eed94be6945acc3eb56eb4ff4c69cbf84918f3ffb41f5117d2dc35a18eed01dd9b800ff40bdf5dfd9b63132a5e9dc0ea51c1e58ff0591b48d08d6786d6edb91',salt:'dd7bdc4663c5af5bf7568b3441b22ae1',createdAt:'2026-01-01T00:00:00.000Z'},
{id:'usr_sol_1',name:'Roberto Lozano (Solicitante)',email:'roberto.lozano@dimer.com.mx',role:'SOLICITANTE',roleId:'role_solicitante',department:'Sistemas',status:'ACTIVO',isVerified:true,passwordHash:'1a8bc4a5a7aebaef93b008de2a239b13c13767d13c1408c793695f9144ee6d9878aa1e2d2ff28f97279252abecdb495dc5406883995d5121363484d8dbba4059',salt:'ffdff96d8a67da1bca99f7d49301cb22',createdAt:'2026-01-01T00:00:00.000Z'},
{id:'usr_fin_1',name:'CP. Laura Finanzas (Tesorería)',email:'finanzas@dimer.com.mx',role:'FINANZAS',roleId:'role_finanzas',department:'Finanzas',status:'ACTIVO',isVerified:true,passwordHash:'1a8bc4a5a7aebaef93b008de2a239b13c13767d13c1408c793695f9144ee6d9878aa1e2d2ff28f97279252abecdb495dc5406883995d5121363484d8dbba4059',salt:'ffdff96d8a67da1bca99f7d49301cb22',createdAt:'2026-01-01T00:00:00.000Z'},
{id:'usr_lec_1',name:'Lic. Auditoria (Solo Lectura Aprobadas)',email:'auditoria@dimer.com.mx',role:'SOLO_LECTURA_APROBADAS',roleId:'role_solo_lectura',department:'Dirección',status:'ACTIVO',isVerified:true,passwordHash:'1a8bc4a5a7aebaef93b008de2a239b13c13767d13c1408c793695f9144ee6d9878aa1e2d2ff28f97279252abecdb495dc5406883995d5121363484d8dbba4059',salt:'ffdff96d8a67da1bca99f7d49301cb22',createdAt:'2026-01-01T00:00:00.000Z'}
];

export const TRAVEL_REQUESTS: TravelRequest[]=[
{id:'req_001',folio:'VIAT-2026-000001',status:'PENDIENTE_APROBACION',userId:'usr_sol_1',requesterName:'Roberto Lozano',department:'Sistemas',requestType:'Viáticos y Gastos de Viaje',detail:'Reunión de cierre con cliente industrial para proyecto de automatización y auditoría en planta.',requestDate:'2026-08-21',urgency:'alta',bossId:'boss_sistemas',bossEmail:'sistemas@dimer.com.mx',bossName:'Ing. Roberto Flores / Autorizaciones TI',startDate:'2026-08-25T00:00:00.000Z',endDate:'2026-08-28T00:00:00.000Z',destination:'Monterrey, N.L.',reason:'Reunión de cierre con cliente industrial para proyecto de automatización y auditoría en planta.',amountRequested:14850,amountAuthorized:null,transportCost:5000,hotelCost:6000,foodCost:3000,miscCost:850,comments:'Incluye vuelos, 3 noches de hospedaje en zona San Pedro y viáticos diarios según tabulador.',approvalToken:'tok_seed_req_001_sistemas',createdAt:'2026-08-21T09:30:00.000Z'},
{id:'req_002',folio:'VIAT-2026-000002',status:'APROBADA',userId:'usr_sol_1',requesterName:'Roberto Lozano',department:'Sistemas',requestType:'Viáticos y Gastos de Viaje',detail:'Participación en Expo Industrial 2026 y visitas técnicas a socios estratégicos.',requestDate:'2026-08-20',urgency:'media',bossId:'boss_sistemas',bossEmail:'sistemas@dimer.com.mx',bossName:'Ing. Roberto Flores / Autorizaciones TI',startDate:'2026-09-02T00:00:00.000Z',endDate:'2026-09-04T00:00:00.000Z',destination:'Guadalajara, Jal.',reason:'Participación en Expo Industrial 2026 y visitas técnicas a socios estratégicos.',amountRequested:12000,amountAuthorized:11000,transportCost:4000,hotelCost:4500,foodCost:2500,miscCost:1000,comments:'Aprobado con ajuste de $1,000 en hotel corporativo con convenio.',approvedBy:'sistemas@dimer.com.mx',approvedAt:'2026-08-20T16:45:00.000Z',createdAt:'2026-08-20T14:15:00.000Z'},
{id:'req_003',folio:'VIAT-2026-000003',status:'PAGADA',userId:'usr_sol_1',requesterName:'Roberto Lozano',department:'Sistemas',requestType:'Servicios y Mantenimiento',detail:'Instalación de servidores y entrega de infraestructura en nuevo centro logístico.',requestDate:'2026-08-08',urgency:'baja',bossId:'boss_sistemas',bossEmail:'sistemas@dimer.com.mx',bossName:'Ing. Roberto Flores / Autorizaciones TI',startDate:'2026-08-10T00:00:00.000Z',endDate:'2026-08-12T00:00:00.000Z',destination:'Querétaro, Qro.',reason:'Instalación de servidores y entrega de infraestructura en nuevo centro logístico.',amountRequested:8500,amountAuthorized:8500,comments:'Dispersado vía transferencia SPEI folio 89123.',approvedBy:'sistemas@dimer.com.mx',approvedAt:'2026-08-08T15:20:00.000Z',createdAt:'2026-08-08T11:00:00.000Z'}
];
export const APPROVAL_TOKENS: ApprovalToken[]=[{id:'tok_init_1',token:'tok_seed_req_001_sistemas',requestId:'req_001',bossId:'boss_sistemas',bossEmail:'sistemas@dimer.com.mx',expiresAt:'2026-09-02T13:10:00.128Z',used:false,createdAt:'2026-08-21T09:30:00.000Z'}];
export const AUDIT_LOGS: AuditLog[]=[];
export const VERIFICATION_CODES = new Map<string,PendingVerification>();
let folioSequence=4;
let readyPromise: Promise<void>|null=null;
let currentSessionUserId:string|null=null;

export function hashPassword(password:string,existingSalt?:string){const salt=existingSalt||crypto.randomBytes(16).toString('hex');return {hash:crypto.pbkdf2Sync(password,salt,10000,64,'sha512').toString('hex'),salt};}
export function verifyPassword(password:string,hash?:string|null,salt?:string|null){try{if(!password||!hash||!salt)return false;const calc=crypto.pbkdf2Sync(password,salt,10000,64,'sha512').toString('hex');return crypto.timingSafeEqual(Buffer.from(calc,'hex'),Buffer.from(hash,'hex'));}catch{return false;}}
export function generateSecureToken(){return crypto.randomBytes(32).toString('hex');}

const toUser=(r:any):StoredUserRecord=>({id:r.id,name:r.name,email:r.email,role:r.role,roleId:r.role_id||undefined,department:r.department||'',status:r.status,isVerified:r.is_verified,passwordHash:r.password_hash,salt:r.salt,createdAt:r.created_at,avatar:r.avatar});
const fromUser=(r:StoredUserRecord)=>({id:r.id,name:r.name,email:r.email.toLowerCase(),role:r.role,role_id:r.roleId||null,department:r.department,status:r.status,is_verified:r.isVerified??true,password_hash:r.passwordHash||'',salt:r.salt||'',created_at:r.createdAt||new Date().toISOString()});
const toDept=(r:any):Department=>({id:r.id,name:r.name,description:r.description||undefined,active:r.active,createdAt:r.created_at});
const fromDept=(r:Department)=>({id:r.id,name:r.name,description:r.description||null,active:r.active,created_at:r.createdAt});
const toRole=(r:any):RoleDefinition=>({id:r.id,name:r.name,description:r.description||undefined,active:r.active,isSystem:r.is_system,permissions:Array.isArray(r.permissions)?r.permissions:[]});
const fromRole=(r:RoleDefinition)=>({id:r.id,name:r.name,description:r.description||null,active:r.active,is_system:r.isSystem??false,permissions:r.permissions});
const toBoss=(r:any):Boss=>({id:r.id,name:r.name,email:r.email,department:r.department||'',active:r.active,createdAt:r.created_at});
const fromBoss=(r:Boss)=>({id:r.id,name:r.name,email:r.email.toLowerCase(),department:r.department,active:r.active,created_at:r.createdAt});
const toReq=(r:any):TravelRequest=>({id:r.id,folio:r.folio,status:r.status,userId:r.user_id,requesterName:r.requester_name,department:r.department,requestType:r.request_type,detail:r.detail,requestDate:r.request_date,urgency:r.urgency,bossId:r.boss_id,bossEmail:r.boss_email,bossName:r.boss_name,startDate:r.start_date,endDate:r.end_date,destination:r.destination,reason:r.reason,amountRequested:Number(r.amount_requested),amountAuthorized:r.amount_authorized==null?null:Number(r.amount_authorized),transportCost:r.transport_cost==null?undefined:Number(r.transport_cost),hotelCost:r.hotel_cost==null?undefined:Number(r.hotel_cost),foodCost:r.food_cost==null?undefined:Number(r.food_cost),miscCost:r.misc_cost==null?undefined:Number(r.misc_cost),comments:r.comments,approvedBy:r.approved_by,approvedAt:r.approved_at,rejectedBy:r.rejected_by,rejectedAt:r.rejected_at,rejectionReason:r.rejection_reason,approvalToken:r.approval_token,createdAt:r.created_at,updatedAt:r.updated_at});
const fromReq=(r:TravelRequest)=>({id:r.id,folio:r.folio,status:r.status,user_id:r.userId,requester_name:r.requesterName||null,department:r.department||null,request_type:r.requestType||null,detail:r.detail||null,request_date:r.requestDate||null,urgency:r.urgency||null,boss_id:r.bossId||null,boss_email:r.bossEmail,boss_name:r.bossName||null,start_date:r.startDate,end_date:r.endDate,destination:r.destination,reason:r.reason,amount_requested:r.amountRequested,amount_authorized:r.amountAuthorized??null,transport_cost:r.transportCost??null,hotel_cost:r.hotelCost??null,food_cost:r.foodCost??null,misc_cost:r.miscCost??null,comments:r.comments??null,approved_by:r.approvedBy||null,approved_at:r.approvedAt||null,rejected_by:r.rejectedBy||null,rejected_at:r.rejectedAt||null,rejection_reason:r.rejectionReason||null,approval_token:r.approvalToken||null,created_at:r.createdAt,updated_at:r.updatedAt||null});
const toToken=(r:any):ApprovalToken=>({id:r.id,token:r.token,requestId:r.request_id,bossId:r.boss_id||undefined,bossEmail:r.boss_email,expiresAt:r.expires_at,used:r.used,usedAt:r.used_at||undefined,action:r.action||undefined,createdAt:r.created_at});
const fromToken=(r:ApprovalToken)=>({id:r.id,token:r.token,request_id:r.requestId||null,boss_id:r.bossId||null,boss_email:r.bossEmail.toLowerCase(),expires_at:r.expiresAt,used:r.used,used_at:r.usedAt||null,action:r.action||null,created_at:r.createdAt});
const toAudit=(r:any):AuditLog=>({id:r.id,requestId:r.request_id,userId:r.user_id,userName:r.user_name,userEmail:r.user_email,action:r.action,details:r.details,createdAt:r.created_at});
const fromAudit=(r:AuditLog)=>({id:r.id,request_id:r.requestId||null,user_id:r.userId,user_name:r.userName||null,user_email:r.userEmail||null,action:r.action,details:r.details||null,created_at:r.createdAt});

async function table<T=any>(name:string){const {data,error}=await supabase.from(name).select('*');if(error)throw error;return (data||[]) as T[];}
async function upsertAll(){
 await Promise.all([
  supabase.from('departments').upsert(DEPARTMENTS.map(fromDept),{onConflict:'id'}),
  supabase.from('roles').upsert(ROLES.map(fromRole),{onConflict:'id'}),
  supabase.from('bosses').upsert(BOSSES.map(fromBoss),{onConflict:'id'}),
  supabase.from('users').upsert(USERS.map(fromUser),{onConflict:'id'}),
  supabase.from('travel_requests').upsert(TRAVEL_REQUESTS.map(fromReq),{onConflict:'id'}),
  supabase.from('approval_tokens').upsert(APPROVAL_TOKENS.map(fromToken),{onConflict:'id'}),
  supabase.from('audit_logs').upsert(AUDIT_LOGS.map(fromAudit),{onConflict:'id'})
 ]);
}

async function hydrate(){
 const [u,d,r,b,t,at,a]=await Promise.all([table('users'),table('departments'),table('roles'),table('bosses'),table('travel_requests'),table('approval_tokens'),table('audit_logs')]);
 if(u.length){USERS.splice(0,USERS.length,...u.map(toUser));DEPARTMENTS.splice(0,DEPARTMENTS.length,...d.map(toDept));ROLES.splice(0,ROLES.length,...r.map(toRole));BOSSES.splice(0,BOSSES.length,...b.map(toBoss));TRAVEL_REQUESTS.splice(0,TRAVEL_REQUESTS.length,...t.map(toReq));APPROVAL_TOKENS.splice(0,APPROVAL_TOKENS.length,...at.map(toToken));AUDIT_LOGS.splice(0,AUDIT_LOGS.length,...a.map(toAudit));const nums=TRAVEL_REQUESTS.map(x=>Number((x.folio||'').split('-').pop())).filter(Number.isFinite);folioSequence=nums.length?Math.max(...nums)+1:1;console.log(`[DIMER DB] Supabase loaded: ${USERS.length} users, ${TRAVEL_REQUESTS.length} requests`);} else {await upsertAll();console.log('[DIMER DB] Supabase was empty; initial DIMER data migrated successfully.');}
}
export function ensureDatabaseReady(){if(!readyPromise)readyPromise=hydrate().catch(e=>{console.error('[DIMER DB] Supabase initialization failed:',e);throw e;});return readyPromise;}
void ensureDatabaseReady();

export async function saveToDisk(){try{await upsertAll();}catch(e){console.error('[DIMER DB] Supabase write failed:',e);}}
export async function loadFromDisk(){await ensureDatabaseReady();}

export function getOrCreateDepartment(rawName:string){const name=rawName.trim();let x=DEPARTMENTS.find(d=>d.name.toLowerCase()===name.toLowerCase());if(x)return x;x={id:`dept_${Date.now()}_${Math.floor(Math.random()*1000)}`,name,description:'Departamento registrado automáticamente',active:true,createdAt:new Date().toISOString()};DEPARTMENTS.push(x);void saveToDisk();return x;}
export function createVerificationCode(p:{email:string;name:string;department:string;roleId?:string;passwordHash:string;salt:string}){const code=crypto.randomInt(100000,1000000).toString();const expiresAt=Date.now()+15*60*1000;const email=p.email.trim().toLowerCase();VERIFICATION_CODES.set(email,{email,code,name:p.name.trim(),department:p.department.trim(),roleId:p.roleId||'role_solicitante',passwordHash:p.passwordHash,salt:p.salt,expiresAt,attempts:0});return {code,expiresAt};}
export function verifyCodeAndActivateUser(email:string,code:string){const clean=email.trim().toLowerCase(),p=VERIFICATION_CODES.get(clean);if(!p)return {success:false,error:'No hay un código de verificación pendiente para este correo. Por favor regístrese nuevamente.'};if(Date.now()>p.expiresAt){VERIFICATION_CODES.delete(clean);return {success:false,error:'El código de verificación ha expirado (límite 15 minutos). Solicite uno nuevo.'};}if(p.code!==code.trim()){p.attempts++;if(p.attempts>=5)VERIFICATION_CODES.delete(clean);return {success:false,error:p.attempts>=5?'Demasiados intentos fallidos. Código invalidado por seguridad.':`Código incorrecto. Te quedan ${5-p.attempts} intentos.`};}const rd=ROLES.find(r=>r.id===p.roleId)||ROLES.find(r=>r.id==='role_solicitante')!;const role:Role=clean==='sistemas@dimer.com.mx'?'ADMIN':rd.id==='role_admin'?'ADMIN':rd.id==='role_solo_lectura'?'SOLO_LECTURA_APROBADAS':'SOLICITANTE';const u:StoredUserRecord={id:`usr_${Date.now()}_${Math.floor(Math.random()*1000)}`,name:p.name,email:clean,role,roleId:rd.id,department:p.department,status:'ACTIVO',isVerified:true,passwordHash:p.passwordHash,salt:p.salt,createdAt:new Date().toISOString()};USERS.push(u);VERIFICATION_CODES.delete(clean);void saveToDisk();return {success:true,user:u};}
export function sanitizeUser(u:StoredUserRecord):User{const admin=u.email.toLowerCase()==='sistemas@dimer.com.mx'||u.role==='ADMIN';const roleId=admin?'role_admin':u.roleId||(u.role==='FINANZAS'?'role_finanzas':u.role==='JEFE'?'role_jefe':u.role==='SOLO_LECTURA_APROBADAS'?'role_solo_lectura':'role_solicitante');const rd=ROLES.find(r=>r.id===roleId);return {id:u.id,name:u.name,email:u.email,department:u.department,role:admin?'ADMIN':u.role,roleId,permissions:admin?ROLES[0].permissions:(rd?.permissions||[]),status:u.status||'ACTIVO',isVerified:u.isVerified??true,avatar:u.avatar,createdAt:u.createdAt};}
export function hasPermission(u:User|StoredUserRecord|null|undefined,p:Permission){if(!u||u.status==='INACTIVO')return false;if(u.role==='ADMIN'||u.email?.toLowerCase()==='sistemas@dimer.com.mx')return true;const r=ROLES.find(x=>x.id===u.roleId);return !!r?.active&&r.permissions.includes(p);}
export function createApprovalToken(requestId:string,bossEmail:string,bossId?:string){const x:ApprovalToken={id:`tok_${Date.now()}_${Math.floor(Math.random()*1000)}`,token:generateSecureToken(),requestId,bossId,bossEmail:bossEmail.toLowerCase(),expiresAt:new Date(Date.now()+7*86400000).toISOString(),used:false,createdAt:new Date().toISOString()};APPROVAL_TOKENS.push(x);void saveToDisk();return x;}
export function validateApprovalToken(token:string){if(!token)return {valid:false,error:'Token de aprobación no proporcionado'};const x=APPROVAL_TOKENS.find(t=>t.token===token);if(!x)return {valid:false,error:'Token de aprobación no encontrado o inválido'};if(x.used)return {valid:false,error:`Este enlace ya fue utilizado previamente el ${new Date(x.usedAt||'').toLocaleString('es-MX')} (${x.action||'PROCESADO'}). Por seguridad, cada token solo puede emplearse una vez.`,tokenRecord:x};if(new Date(x.expiresAt).getTime()<Date.now())return {valid:false,error:'El enlace de aprobación ha expirado. Contacte al solicitante para emitir una revalidación.',tokenRecord:x};const request=TRAVEL_REQUESTS.find(r=>r.id===x.requestId);if(!request)return {valid:false,error:'La solicitud asociada a este token ya no existe',tokenRecord:x};return {valid:true,tokenRecord:x,request};}
export function consumeApprovalToken(token:string,action:'APROBADA'|'RECHAZADA'){const x=APPROVAL_TOKENS.find(t=>t.token===token);if(!x||x.used)return false;x.used=true;x.usedAt=new Date().toISOString();x.action=action;void saveToDisk();return true;}
export function getCurrentUser(){if(!currentSessionUserId)return null;const x=USERS.find(u=>u.id===currentSessionUserId);return x?sanitizeUser(x):null;}
export function clearCurrentUser(){currentSessionUserId=null;}
export function setCurrentUser(x:string|User|null):User|null{if(x===null){currentSessionUserId=null;return null;}if(typeof x==='string'){const c=x.trim().toLowerCase(),u=USERS.find(v=>v.email.toLowerCase()===c||v.id===x);if(u){currentSessionUserId=u.id;return sanitizeUser(u);}return null;}currentSessionUserId=x.id;const u=USERS.find(v=>v.id===x.id);return u?sanitizeUser(u):x;}
export function generateNextFolio(){const year=new Date().getFullYear();return `VIAT-${year}-${String(folioSequence++).padStart(6,'0')}`;}
export function recordAuditLog(p:{requestId?:string|null;userId:string;action:string;details?:Record<string,any>}):AuditLog{const u=USERS.find(x=>x.id===p.userId);const x:AuditLog={id:`aud_${Date.now()}_${Math.floor(Math.random()*1000)}`,requestId:p.requestId||null,userId:p.userId,userName:u?.name||'Sistema / Token Seguro',userEmail:u?.email||p.details?.userEmail||'N/A',action:p.action,details:p.details||null,createdAt:new Date().toISOString()};AUDIT_LOGS.unshift(x);void saveToDisk();return x;}
export function getPopulatedRequests(){return TRAVEL_REQUESTS.map(r=>({...r,user:USERS.find(u=>u.id===r.userId)?sanitizeUser(USERS.find(u=>u.id===r.userId)!):undefined}));}
