import crypto from 'crypto';
import { supabase } from './supabase.js';
import type { User, TravelRequest, AuditLog, RoleDefinition, Department, Boss, ApprovalToken, Permission, Role } from '../src/types';

export interface StoredUserRecord extends User { passwordHash?: string; salt?: string; }

export const ALL_SYSTEM_PERMISSIONS: {id:Permission;label:string;description:string;category:string}[] = [
  ['ver_solicitudes','Ver mis solicitudes','Consultar solicitudes de viáticos','Viáticos'],['crear_solicitudes','Crear solicitudes','Generar solicitudes','Viáticos'],['editar_solicitudes','Editar solicitudes','Modificar solicitudes permitidas','Viáticos'],['cancelar_solicitudes','Cancelar solicitudes','Cancelar solicitudes propias','Viáticos'],['aprobar_solicitudes','Aprobar solicitudes','Dictaminar y autorizar viáticos','Aprobaciones'],['ver_todas_solicitudes','Ver todas las solicitudes','Consultar solicitudes corporativas','Aprobaciones'],['administrar_usuarios','Administrar usuarios','Gestionar usuarios','Administración'],['administrar_departamentos','Administrar departamentos','Gestionar departamentos','Administración'],['administrar_jefes','Administrar jefes','Gestionar aprobadores','Administración'],['administrar_roles','Administrar roles','Gestionar roles y permisos','Administración'],['ver_reportes','Ver reportes y Finanzas','Consultar reportes y finanzas','Finanzas'],['administrar_configuracion','Administrar configuración','Gestionar configuración','Administración']
].map(([id,label,description,category])=>({id:id as Permission,label,description,category}));

const toUser=(r:any):StoredUserRecord=>({id:r.id,name:r.name,email:r.email,role:r.role,roleId:r.role_id||undefined,department:r.department||'',status:r.status,isVerified:r.is_verified,passwordHash:r.password_hash,salt:r.salt,createdAt:r.created_at,avatar:r.avatar});
const toDept=(r:any):Department=>({id:r.id,name:r.name,description:r.description||undefined,active:Boolean(r.active),createdAt:r.created_at});
const toRole=(r:any):RoleDefinition=>({id:r.id,name:r.name,description:r.description||undefined,active:Boolean(r.active),isSystem:Boolean(r.is_system),permissions:Array.isArray(r.permissions)?r.permissions:[]});
const toBoss=(r:any):Boss=>({id:r.id,name:r.name,email:r.email,department:r.department||'',active:Boolean(r.active),createdAt:r.created_at});
const toReq=(r:any):TravelRequest=>({id:r.id,folio:r.folio,status:r.status,userId:r.user_id,requesterName:r.requester_name,department:r.department,requestType:r.request_type,detail:r.detail,requestDate:r.request_date,urgency:r.urgency,bossId:r.boss_id,bossEmail:r.boss_email||'',bossName:r.boss_name,startDate:r.start_date,endDate:r.end_date,destination:r.destination||'',reason:r.reason||'',amountRequested:r.amount_requested==null?0:Number(r.amount_requested),amountAuthorized:r.amount_authorized==null?null:Number(r.amount_authorized),transportCost:r.transport_cost==null?0:Number(r.transport_cost),hotelCost:r.hotel_cost==null?0:Number(r.hotel_cost),foodCost:r.food_cost==null?0:Number(r.food_cost),miscCost:r.misc_cost==null?0:Number(r.misc_cost),comments:r.comments,approvedBy:r.approved_by,approvedAt:r.approved_at,rejectedBy:r.rejected_by,rejectedAt:r.rejected_at,rejectionReason:r.rejection_reason,approvalToken:r.approval_token,createdAt:r.created_at,updatedAt:r.updated_at});
const toToken=(r:any):ApprovalToken=>({id:r.id,token:r.token,requestId:r.request_id,bossId:r.boss_id||undefined,bossEmail:r.boss_email||'',expiresAt:r.expires_at,used:Boolean(r.used),usedAt:r.used_at||undefined,action:r.action||undefined,createdAt:r.created_at});
const toAudit=(r:any):AuditLog=>({id:r.id,requestId:r.request_id,userId:r.user_id,userName:r.user_name,userEmail:r.user_email,action:r.action,details:r.details,createdAt:r.created_at});

export function hashPassword(password:string,existingSalt?:string){const salt=existingSalt||crypto.randomBytes(16).toString('hex');return {hash:crypto.pbkdf2Sync(password,salt,10000,64,'sha512').toString('hex'),salt};}
export function verifyPassword(password:string,hash?:string|null,salt?:string|null){try{if(!password||!hash||!salt)return false;const calc=crypto.pbkdf2Sync(password,salt,10000,64,'sha512').toString('hex');const a=Buffer.from(calc,'hex'),b=Buffer.from(hash,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b);}catch{return false;}}
export function generateSecureToken(){return crypto.randomBytes(32).toString('hex');}

export function sanitizeUser(u:StoredUserRecord,role?:RoleDefinition):User{const roleId=u.roleId||(u.role==='ADMIN'?'role_admin':u.role==='JEFE'?'role_jefe':u.role==='FINANZAS'?'role_finanzas':u.role==='SOLO_LECTURA_APROBADAS'?'role_solo_lectura':'role_solicitante');const perms=role?.permissions||[];return {id:u.id,name:u.name,email:u.email,department:u.department||'',role:u.role,roleId,permissions:u.role==='ADMIN'?ALL_SYSTEM_PERMISSIONS.map(p=>p.id):perms,status:u.status,isVerified:u.isVerified??true,avatar:u.avatar,createdAt:u.createdAt};}

export async function getUserById(id:string){const {data,error}=await supabase.from('users').select('*').eq('id',id).maybeSingle();if(error)throw error;return data?toUser(data):null;}
export async function getUserByEmail(email:string){const {data,error}=await supabase.from('users').select('*').eq('email',email.trim().toLowerCase()).maybeSingle();if(error)throw error;return data?toUser(data):null;}
export async function listUsers(){const {data,error}=await supabase.from('users').select('*').order('created_at',{ascending:false});if(error)throw error;const roles=await listRoles();return (data||[]).map(toUser).map(u=>sanitizeUser(u,roles.find(r=>r.id===u.roleId)));}
export async function insertUser(u:StoredUserRecord){const {data,error}=await supabase.from('users').insert({id:u.id,name:u.name,email:u.email.toLowerCase(),role:u.role,role_id:u.roleId||'role_solicitante',department:u.department||'General',status:u.status,is_verified:u.isVerified??true,password_hash:u.passwordHash||'',salt:u.salt||'',created_at:u.createdAt||new Date().toISOString()}).select('*').single();if(error)throw error;return toUser(data);}
export async function updateUser(id:string,p:Partial<StoredUserRecord>){const row:any={};for(const [k,v] of Object.entries(p)){const m:any={name:'name',email:'email',role:'role',roleId:'role_id',department:'department',status:'status',isVerified:'is_verified',passwordHash:'password_hash',salt:'salt'};if(m[k]!==undefined&&v!==undefined)row[m[k]]=k==='email'?String(v).toLowerCase():v;}const {data,error}=await supabase.from('users').update(row).eq('id',id).select('*').single();if(error)throw error;return toUser(data);}
export async function deleteUser(id:string){const {error}=await supabase.from('users').delete().eq('id',id);if(error)throw error;}

export async function listDepartments(){const {data,error}=await supabase.from('departments').select('*').order('name');if(error)throw error;return (data||[]).map(toDept);}
export async function getOrCreateDepartment(name:string){const clean=name.trim()||'General';const {data,error}=await supabase.from('departments').select('*').ilike('name',clean).maybeSingle();if(error)throw error;if(data)return toDept(data);const {data:created,error:e}=await supabase.from('departments').insert({id:`dept_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`,name:clean,description:'Departamento registrado automáticamente',active:true,created_at:new Date().toISOString()}).select('*').single();if(e)throw e;return toDept(created);}
export async function createDepartment(name:string,description?:string){return getOrCreateDepartment(name).then(async d=>{if(d.description==='Departamento registrado automáticamente'&&description){const {data,error}=await supabase.from('departments').update({description}).eq('id',d.id).select('*').single();if(error)throw error;return toDept(data);}return d;});}
export async function updateDepartment(id:string,p:any){const {data,error}=await supabase.from('departments').update({name:p.name,description:p.description,active:p.active}).eq('id',id).select('*').single();if(error)throw error;return toDept(data);}

export async function listBosses(){const {data,error}=await supabase.from('bosses').select('*').order('name');if(error)throw error;return (data||[]).map(toBoss);}
export async function getBossById(id:string){const {data,error}=await supabase.from('bosses').select('*').eq('id',id).maybeSingle();if(error)throw error;return data?toBoss(data):null;}
export async function createBoss(name:string,email:string,department:string){const {data,error}=await supabase.from('bosses').insert({id:`boss_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`,name:name.trim(),email:email.trim().toLowerCase(),department:department.trim(),active:true,created_at:new Date().toISOString()}).select('*').single();if(error)throw error;return toBoss(data);}
export async function updateBoss(id:string,p:any){const row:any={};if(p.name!==undefined)row.name=p.name;if(p.email!==undefined)row.email=p.email.toLowerCase();if(p.department!==undefined)row.department=p.department;if(p.active!==undefined)row.active=Boolean(p.active);const {data,error}=await supabase.from('bosses').update(row).eq('id',id).select('*').single();if(error)throw error;return toBoss(data);}
export async function deleteBoss(id:string){const {error}=await supabase.from('bosses').delete().eq('id',id);if(error)throw error;}

export async function listRoles(){const {data,error}=await supabase.from('roles').select('*').order('name');if(error)throw error;return (data||[]).map(toRole);}
export async function createRole(p:any){const {data,error}=await supabase.from('roles').insert({id:`role_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`,name:p.name.trim(),description:p.description?.trim()||null,permissions:Array.isArray(p.permissions)?p.permissions:['ver_solicitudes'],active:true,is_system:false,created_at:new Date().toISOString()}).select('*').single();if(error)throw error;return toRole(data);}
export async function updateRole(id:string,p:any){const {data,error}=await supabase.from('roles').update({name:p.name,description:p.description,permissions:p.permissions,active:p.active}).eq('id',id).select('*').single();if(error)throw error;return toRole(data);}

export async function listRequests(){const {data,error}=await supabase.from('travel_requests').select('*').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map(toReq);}
export async function getRequest(idOrFolio:string){const {data,error}=await supabase.from('travel_requests').select('*').or(`id.eq.${idOrFolio},folio.eq.${idOrFolio}`).maybeSingle();if(error)throw error;return data?toReq(data):null;}
export async function getPopulatedRequests(){const rs=await listRequests();const ids=[...new Set(rs.map(r=>r.userId).filter(Boolean))];if(!ids.length)return rs;const {data,error}=await supabase.from('users').select('*').in('id',ids);if(error)throw error;const roles=await listRoles();const users=new Map((data||[]).map((r:any)=>[r.id,sanitizeUser(toUser(r),roles.find(x=>x.id===r.role_id))]));return rs.map(r=>({...r,user:users.get(r.userId)}));}
export async function insertRequest(r:TravelRequest){const {data,error}=await supabase.from('travel_requests').insert({id:r.id,folio:r.folio,status:r.status,user_id:r.userId,requester_name:r.requesterName||null,department:r.department||null,request_type:r.requestType||null,detail:r.detail||null,request_date:r.requestDate||null,urgency:r.urgency||null,boss_id:r.bossId||null,boss_email:r.bossEmail||null,boss_name:r.bossName||null,start_date:r.startDate||null,end_date:r.endDate||null,destination:r.destination||null,reason:r.reason||null,amount_requested:r.amountRequested,amount_authorized:r.amountAuthorized??null,transport_cost:r.transportCost??0,hotel_cost:r.hotelCost??0,food_cost:r.foodCost??0,misc_cost:r.miscCost??0,comments:r.comments??null,approved_by:r.approvedBy||null,approved_at:r.approvedAt||null,created_at:r.createdAt||new Date().toISOString(),approval_token:r.approvalToken||null,rejected_by:r.rejectedBy||null,rejected_at:r.rejectedAt||null,rejection_reason:r.rejectionReason||null,updated_at:r.updatedAt||null}).select('*').single();if(error)throw error;return toReq(data);}
export async function updateRequest(id:string,p:any){const map:any={requesterName:'requester_name',department:'department',requestType:'request_type',detail:'detail',requestDate:'request_date',urgency:'urgency',bossId:'boss_id',bossEmail:'boss_email',bossName:'boss_name',startDate:'start_date',endDate:'end_date',destination:'destination',reason:'reason',amountRequested:'amount_requested',amountAuthorized:'amount_authorized',transportCost:'transport_cost',hotelCost:'hotel_cost',foodCost:'food_cost',miscCost:'misc_cost',comments:'comments',approvedBy:'approved_by',approvedAt:'approved_at',rejectedBy:'rejected_by',rejectedAt:'rejected_at',rejectionReason:'rejection_reason',approvalToken:'approval_token',status:'status',updatedAt:'updated_at'};const row:any={};for(const k of Object.keys(map))if(p[k]!==undefined)row[map[k]]=p[k];const {data,error}=await supabase.from('travel_requests').update(row).eq('id',id).select('*').single();if(error)throw error;return toReq(data);}
export async function deleteRequest(id:string){const {error}=await supabase.from('travel_requests').delete().eq('id',id);if(error)throw error;}

export async function generateNextFolio(){const {data,error}=await supabase.rpc('generate_next_travel_folio',{target_year:new Date().getFullYear()});if(error||typeof data!=='string')throw new Error(`Error generando folio PostgreSQL: ${error?.message||'RPC no disponible'}`);return data;}
export async function createApprovalToken(requestId:string,bossEmail:string,bossId?:string){const {data,error}=await supabase.from('approval_tokens').insert({id:`apptok_${Date.now()}_${crypto.randomBytes(8).toString('hex')}`,token:`tok_${crypto.randomBytes(32).toString('hex')}`,request_id:requestId,boss_id:bossId||null,boss_email:bossEmail.trim().toLowerCase(),expires_at:new Date(Date.now()+7*86400000).toISOString(),used:false,created_at:new Date().toISOString(),used_at:null,action:null}).select('*').single();if(error)throw error;return toToken(data);}
export async function validateApprovalToken(token:string){const {data,error}=await supabase.from('approval_tokens').select('*').eq('token',token.trim()).maybeSingle();if(error)throw error;if(!data)return {valid:false as const,error:'Token inválido o no encontrado'};const t=toToken(data);if(t.used)return {valid:false as const,error:`Este enlace ya fue utilizado previamente para ${t.action||'procesar'} la solicitud.`,tokenRecord:t};if(t.expiresAt&&new Date(t.expiresAt).getTime()<Date.now())return {valid:false as const,error:'Este enlace de autorización ha expirado.',tokenRecord:t};const request=await getRequest(t.requestId);if(!request)return {valid:false as const,error:'No se encontró la solicitud asociada al token',tokenRecord:t};return {valid:true as const,tokenRecord:t,request};}
export async function processApprovalTokenAction(token:string,action:'APROBADA'|'RECHAZADA',amountAuthorized?:number|null,comments?:string|null){const {data,error}=await supabase.rpc('process_approval_token_action',{p_token:token,p_action:action,p_amount_authorized:amountAuthorized??null,p_comments:comments??null});if(error)throw error;if(!data||data.success!==true)throw new Error('PostgreSQL no confirmó la autorización');return data;}
export async function recordAuditLog(p:{requestId?:string|null;userId:string;action:string;details?:Record<string,unknown>}){const user=await getUserById(p.userId);const {data,error}=await supabase.from('audit_logs').insert({id:`aud_${Date.now()}_${crypto.randomBytes(5).toString('hex')}`,request_id:p.requestId||null,user_id:p.userId,user_name:user?.name||null,user_email:user?.email||null,action:p.action,details:p.details||null,created_at:new Date().toISOString()}).select('*').single();if(error)throw error;return toAudit(data);}
export async function listAuditLogs(){const {data,error}=await supabase.from('audit_logs').select('*').order('created_at',{ascending:false});if(error)throw error;return (data||[]).map(toAudit);}
export async function createVerificationCode(p:{email:string;name:string;department:string;roleId:string;passwordHash:string;salt:string}){const code=crypto.randomInt(100000,1000000).toString();const expiresAt=new Date(Date.now()+15*60*1000).toISOString();const {error}=await supabase.from('verification_codes').upsert({email:p.email.toLowerCase(),code,name:p.name,department:p.department,role_id:p.roleId,password_hash:p.passwordHash,salt:p.salt,expires_at:expiresAt,attempts:0,created_at:new Date().toISOString()},{onConflict:'email'});if(error)throw error;return {code,expiresAt};}
export async function verifyCodeAndActivateUser(email:string,code:string){const clean=email.trim().toLowerCase();const {data,error}=await supabase.from('verification_codes').select('*').eq('email',clean).maybeSingle();if(error)throw error;if(!data)return {success:false,error:'No hay un código pendiente para este correo.'};if(new Date(data.expires_at).getTime()<Date.now())return {success:false,error:'El código ha expirado.'};if(Number(data.attempts||0)>=5)return {success:false,error:'Demasiados intentos. Solicita un nuevo código.'};if(String(data.code)!==code.trim()){await supabase.from('verification_codes').update({attempts:Number(data.attempts||0)+1}).eq('email',clean);return {success:false,error:'Código de verificación incorrecto.'};}const id=`usr_${Date.now()}_${crypto.randomBytes(5).toString('hex')}`;const {data:user,error:e}=await supabase.from('users').insert({id,name:data.name,email:clean,role:'SOLICITANTE',role_id:data.role_id||'role_solicitante',department:data.department,status:'ACTIVO',is_verified:true,password_hash:data.password_hash,salt:data.salt,created_at:new Date().toISOString()}).select('*').single();if(e)throw e;await supabase.from('verification_codes').delete().eq('email',clean);return {success:true,user:toUser(user)};}
export function hasPermission(u:User|undefined,p:Permission){return !!u&&u.status==='ACTIVO'&&(u.role==='ADMIN'||u.permissions?.includes(p));}
