import nodemailer from 'nodemailer';
import type { TravelRequest, User, EmailLog } from '../src/types';

export const outboxLogs: EmailLog[] = [];
function credentials(){const host=process.env.SMTP_HOST?.trim()||process.env.EMAIL_HOST?.trim()||'smtp.gmail.com';const port=parseInt(process.env.SMTP_PORT||process.env.EMAIL_PORT||'465',10);const user=(process.env.SMTP_USER||process.env.SMTP_USERNAME||process.env.EMAIL_USER||process.env.GMAIL_USER||'').trim().replace(/^["']|["']$/g,'');const pass=(process.env.SMTP_PASS||process.env.SMTP_PASSWORD||process.env.EMAIL_PASS||process.env.EMAIL_PASSWORD||process.env.GMAIL_APP_PASSWORD||process.env.GMAIL_PASSWORD||'').trim().replace(/^["']|["']$/g,'').replace(/\s+/g,'');return {host,port,user,pass,secure:process.env.SMTP_SECURE==='true'||port===465};}
export function getMailTransporter(){const c=credentials();if(!c.user||!c.pass)return null;if(c.host.toLowerCase()==='smtp.gmail.com')return nodemailer.createTransport({service:'gmail',auth:{user:c.user,pass:c.pass},tls:{rejectUnauthorized:false}});return nodemailer.createTransport({host:c.host,port:c.port,secure:c.secure,auth:{user:c.user,pass:c.pass},tls:{rejectUnauthorized:false},connectionTimeout:15000,greetingTimeout:15000,socketTimeout:20000});}
export function getFromAddress(customFrom?:string){if(customFrom?.trim())return customFrom.trim();const from=process.env.SMTP_FROM||process.env.EMAIL_FROM||process.env.MAIL_FROM;if(from?.trim())return from.trim();const c=credentials();return `Dimer Notificaciones <${c.user||'sistemas@dimer.com.mx'}>`;}
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!));
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(Number(n||0));
function layout(title:string,body:string){return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><style>body{font-family:Arial,sans-serif;background:#f1f5f9;padding:24px;color:#0f172a}.card{max-width:650px;margin:auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden}.head{background:#0f172a;color:#fff;padding:24px}.body{padding:28px}.btn{display:inline-block;padding:12px 18px;color:#fff;text-decoration:none;border-radius:6px;margin:4px}.ok{background:#059669}.bad{background:#dc2626}.foot{padding:16px;background:#f8fafc;color:#64748b;font-size:11px;text-align:center}</style></head><body><div class="card"><div class="head"><h2>${esc(title)}</h2></div><div class="body">${body}</div><div class="foot">Sistema de Viáticos Dimer © 2026</div></div></body></html>`;}
export function buildBossApprovalEmailHtml(p:{request:TravelRequest;user:User;approveUrl:string;rejectUrl:string;token:string}){const r=p.request;return layout(`Solicitud por autorizar - ${r.folio}`,`<p>Estimado/a jefe aprobador:</p><p><strong>${esc(p.user.name)}</strong> (${esc(p.user.email)}) solicita autorización de viáticos.</p><p><strong>Departamento:</strong> ${esc(r.department)}<br><strong>Destino:</strong> ${esc(r.destination)}<br><strong>Periodo:</strong> ${esc(r.startDate)} al ${esc(r.endDate)}<br><strong>Detalle:</strong> ${esc(r.detail||r.reason)}</p><p style="font-size:24px;text-align:center"><strong>${money(r.amountRequested)} MXN</strong></p><p style="text-align:center"><a class="btn ok" href="${p.approveUrl}">APROBAR</a><a class="btn bad" href="${p.rejectUrl}">RECHAZAR</a></p>`);}
export function buildSystemsApprovedEmailHtml(p:{request:TravelRequest;user:User;approverName:string;approverEmail:string;approvedAt:string}){const r=p.request;return layout(`Solicitud aprobada - ${r.folio}`,`<p>La solicitud fue aprobada.</p><p><strong>Solicitante:</strong> ${esc(p.user.name)} (${esc(p.user.email)})<br><strong>Aprobador:</strong> ${esc(p.approverName)} (${esc(p.approverEmail)})<br><strong>Fecha:</strong> ${esc(new Date(p.approvedAt).toLocaleString('es-MX'))}<br><strong>Destino:</strong> ${esc(r.destination)}</p><p style="font-size:24px;text-align:center"><strong>${money(r.amountAuthorized??r.amountRequested)} MXN</strong></p>`);}
export function buildVerificationEmailHtml(p:{name:string;email:string;code:string;expiresMinutes?:number}){return layout('Código de verificación Dimer',`<p>Hola <strong>${esc(p.name)}</strong>.</p><p>Tu código para verificar ${esc(p.email)} es:</p><p style="font-size:36px;text-align:center;letter-spacing:8px"><strong>${esc(p.code)}</strong></p><p>Válido por ${p.expiresMinutes||15} minutos.</p>`);}
export function buildNewAccountAdminEmailHtml(p:{user:{name:string;email:string;department:string;role:string};registeredAt:string}){return layout('Nueva cuenta registrada',`<p><strong>${esc(p.user.name)}</strong> registró ${esc(p.user.email)}.</p><p>Departamento: ${esc(p.user.department)}<br>Rol inicial: ${esc(p.user.role)}<br>Fecha: ${esc(p.registeredAt)}</p>`);}
export function buildTokenApprovalResultPageHtml(p:{status:string;request?:TravelRequest;actionTaken?:string;errorMessage?:string;processedBy?:string;processedAt?:string}){const r=p.request;return layout(p.status==='APROBADA'?'Solicitud aprobada':p.status==='RECHAZADA'?'Solicitud rechazada':'Resultado del dictamen',`<p>${esc(p.errorMessage||`Estado: ${p.status}`)}</p>${r?`<p><strong>Folio:</strong> ${esc(r.folio)}<br><strong>Solicitante:</strong> ${esc(r.requesterName)}<br><strong>Procesado por:</strong> ${esc(p.processedBy||r.approvedBy||r.rejectedBy||r.bossEmail)}<br><strong>Fecha:</strong> ${esc(p.processedAt||new Date().toISOString())}</p>`:''}`);}
export async function sendEmail(p:{to:string;subject:string;html:string;from?:string;replyTo?:string;requestId?:string;folio?:string}):Promise<{success:boolean;logId:string;status:'ENVIADO'|'SIMULADO'|'FALLIDO';error?:string}>{const logId=`MAIL-${Date.now()}-${Math.floor(Math.random()*100000)}`;const transporter=getMailTransporter();if(!transporter){const error='Faltan credenciales SMTP';return {success:false,logId,status:process.env.VERCEL||process.env.NODE_ENV==='production'?'FALLIDO':'SIMULADO',error};}try{await transporter.sendMail({from:getFromAddress(p.from),replyTo:p.replyTo,to:p.to,subject:p.subject,html:p.html});return {success:true,logId,status:'ENVIADO'};}catch(e:any){return {success:false,logId,status:'FALLIDO',error:e?.message||'Error SMTP'};}}
