import crypto from 'crypto';
import type { Request, Response } from 'express';
import { getUserById, listRoles, sanitizeUser, hasPermission, validateApprovalToken, processApprovalTokenAction, getRequest } from './db.js';
import { buildSystemsApprovedEmailHtml, buildTokenApprovalResultPageHtml, sendEmail } from './mailService.js';

const PUBLIC_EXACT = new Set(['/api/health','/health','/api/diagnostic','/diagnostic','/api/auth/login','/auth/login','/api/login','/login','/api/auth/register-init','/api/auth/verify-code','/api/auth/resend-code','/api/departments']);
const ADMIN_EXACT = new Set(['/api/outbox','/api/stats','/api/code-artifacts','/api/permissions','/api/roles']);
const CONFIG_EXACT = new Set(['/api/smtp/status','/api/smtp/test','/api/audit-logs']);
const PROTECTED_REQUEST_FIELDS = new Set(['id','folio','userId','status','approvalToken','approvedBy','approvedAt','rejectedBy','rejectedAt','rejectionReason','createdAt','updatedAt']);
function pathOf(req:Request){const raw=String((req as any).originalUrl||(req as any).url||'/');return new URL(raw,'http://localhost').pathname;}
function parseCookies(req:Request){const raw=String(req.headers.cookie||'');return Object.fromEntries(raw.split(';').map(x=>x.trim()).filter(Boolean).map(x=>{const i=x.indexOf('=');return i<0?[x,'']:[x.slice(0,i),decodeURIComponent(x.slice(i+1))];}));}
function verifyJwt(token:string){const secret=process.env.JWT_SECRET;if(!secret)return null;const p=token.split('.');if(p.length!==3)return null;const expected=crypto.createHmac('sha256',secret).update(`${p[0]}.${p[1]}`).digest('base64url');const a=Buffer.from(expected),b=Buffer.from(p[2]);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;try{const payload=JSON.parse(Buffer.from(p[1],'base64url').toString('utf8')) as {sub?:string;exp?:number};if(!payload.sub||!payload.exp||payload.exp<Math.floor(Date.now()/1000))return null;return payload;}catch{return null;}}
async function currentUser(req:Request){const cookies=parseCookies(req);const bearer=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();const token=cookies.dimer_session||bearer;if(!token)return null;const payload=verifyJwt(token);if(!payload?.sub)return null;try{const u=await getUserById(payload.sub);if(!u||u.status!=='ACTIVO')return null;const roles=await listRoles();return sanitizeUser(u,roles,roles);}catch{return null;}}
function originAllowed(req:Request){const origin=String(req.headers.origin||'').trim();if(!origin)return true;const configured=process.env.APP_URL?.trim().replace(/\/+$/,'');if(configured)return origin===configured;const production=process.env.VERCEL_PROJECT_PRODUCTION_URL||process.env.VERCEL_URL;if(production)return origin===`https://${production}`;return true;}
function escapeHtml(v:unknown){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]!));}
export async function securityGate(req:Request,res:Response,next:(err?:unknown)=>void){const path=pathOf(req);if(req.method!=='GET'&&req.method!=='HEAD'&&req.method!=='OPTIONS'){const site=String(req.headers['sec-fetch-site']||'');if(site==='cross-site'||!originAllowed(req))return res.status(403).json({error:'Origen no permitido'});}if(PUBLIC_EXACT.has(path))return next();if(path.startsWith('/api/')){const user=await currentUser(req);if(!user)return res.status(401).json({error:'Autenticación requerida'});if(ADMIN_EXACT.has(path)&&!hasPermission(user,'administrar_usuarios')&&!hasPermission(user,'administrar_configuracion')&&!hasPermission(user,'ver_reportes'))return res.status(403).json({error:'Permiso de administración requerido'});if(CONFIG_EXACT.has(path)&&!hasPermission(user,'administrar_configuracion'))return res.status(403).json({error:'Permiso de configuración requerido'});if(path==='/api/me')return res.json({user,appUrl:process.env.APP_URL||undefined,finanzasEmail:process.env.FINANZAS_EMAIL||'finanzas@dimer.com.mx',systemsEmail:'sistemas@dimer.com.mx'});const requestMatch=/^\/api\/requests\/([^/]+)$/.exec(path);if(requestMatch&&(req.method==='PUT'||req.method==='PATCH')){const r=await getRequest(decodeURIComponent(requestMatch[1]));if(!r)return res.status(404).json({error:'Solicitud no encontrada'});if(!hasPermission(user,'administrar_configuracion')&&(r.userId!==user.id||!['PENDIENTE_APROBACION','CORRECCION_SOLICITADA','BORRADOR'].includes(r.status)))return res.status(403).json({error:'No puedes modificar esta solicitud en su estado actual'});if(req.body&&typeof req.body==='object')for(const key of PROTECTED_REQUEST_FIELDS)delete req.body[key];}(req as any).dimerUser=user;}return next();}
