import React, { useState, useEffect } from 'react';
import { Send, Calendar, MapPin, DollarSign, Mail, FileText, AlertCircle, CheckCircle2, Sparkles, Calculator, ShieldCheck, Building, ArrowRight, UserCheck, Clock, Layers, Flame, Check, Copy, Code, LogOut } from 'lucide-react';
import EmailAutocompleteInput from './EmailAutocompleteInput';
import { safeFetchJson } from '../utils/apiHelper';
import type { CompanyEmployee } from '../data/companyDirectory';
import type { User, TravelRequest, Boss, Department } from '../types';

interface SolicitarViewProps { currentUser: User | null; onRequestCreated: (newRequest: TravelRequest) => void; onNavigateToApprovals: (requestId: string) => void; onLogout?: () => void; }

export default function SolicitarView({ currentUser, onRequestCreated, onNavigateToApprovals, onLogout }: SolicitarViewProps) {
  const [bosses, setBosses] = useState<Boss[]>([]);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [requesterName, setRequesterName] = useState(currentUser?.name || '');
  const [department, setDepartment] = useState(currentUser?.department || 'Ventas');
  const requestTypes = ['Viáticos y Gastos de Viaje','Equipo de Cómputo / Hardware','Licencias de Software y Sistemas','Servicios Externos y Consultoría','Insumos, Papelería y Oficina','Transporte, Combustible y Logística','Mantenimiento e Instalaciones','Capacitación y Cursos','Otra Solicitud Especial'];
  const [requestType, setRequestType] = useState('Viáticos y Gastos de Viaje');
  const [detail, setDetail] = useState('');
  const todayStr = new Date().toISOString().split('T')[0];
  const [requestDate, setRequestDate] = useState(todayStr);
  const [depositDate, setDepositDate] = useState(todayStr);
  const [urgency, setUrgency] = useState<'baja'|'media'|'alta'>('media');
  const [selectedBossId, setSelectedBossId] = useState<string>('');
  const [bossEmail, setBossEmail] = useState('');
  const [bossName, setBossName] = useState('');
  const [directorySearch, setDirectorySearch] = useState('');
  const [startDate, setStartDate] = useState(todayStr);
  const [endDate, setEndDate] = useState(todayStr);
  const [destination, setDestination] = useState('');
  const [amountRequested, setAmountRequested] = useState('');
  const [comments, setComments] = useState('');
  const [showCalculator, setShowCalculator] = useState(false);
  const [calcHotel, setCalcHotel] = useState(6000);
  const [calcTransport, setCalcTransport] = useState(5000);
  const [calcFood, setCalcFood] = useState(3000);
  const [calcMisc, setCalcMisc] = useState(850);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copiedJson, setCopiedJson] = useState(false);
  const [successResult, setSuccessResult] = useState<{request: TravelRequest; approvalToken?: string; mailResult?: any; automationJson?: any;} | null>(null);

  useEffect(() => {
    fetch('/api/bosses').then(r=>r.json()).then((data: Boss[])=>{const active=data.filter(b=>b.active);setBosses(active);if(active.length){const first=active[0];setSelectedBossId(first.id);setBossEmail(first.email);setBossName(first.name);}}).catch(err=>console.error('Error cargando jefes:',err));
    fetch('/api/departments').then(r=>r.json()).then((data: Department[])=>{if(Array.isArray(data))setDepartments(data.filter(d=>d.active));}).catch(err=>console.error('Error cargando departamentos:',err));
  },[]);
  useEffect(()=>{if(currentUser){if(!requesterName)setRequesterName(currentUser.name);if(!department&&currentUser.department)setDepartment(currentUser.department);}},[currentUser]);
  const handleBossChange=(bossId:string)=>{setSelectedBossId(bossId);const found=bosses.find(b=>b.id===bossId);if(found){setBossEmail(found.email);setBossName(found.name);}};
  const popularDestinations=['Monterrey, N.L. - Planta Industrial','Guadalajara, Jal. - Parque Tecnológico','Querétaro, Qro. - Parque Logístico','Ciudad de México (CDMX) - Corporativo','Toluca, Edo. Méx. - Centro de Distribución','Oficinas Centrales Dimer'];
  const calculateDays=()=>{if(!startDate||!endDate)return 0;const start=new Date(startDate);const end=new Date(endDate);const diffTime=end.getTime()-start.getTime();if(diffTime<0)return -1;return Math.ceil(diffTime/86400000)+1;};
  const travelDays=calculateDays();
  const applyCalculatorTotal=()=>{const total=(calcHotel||0)+(calcTransport||0)+(calcFood||0)+(calcMisc||0);setAmountRequested(String(total));const breakdownText=`Desglose estimado: Hospedaje ($${calcHotel}), Transporte ($${calcTransport}), Alimentos ($${calcFood}), Imprevistos/Taxis ($${calcMisc}).`;setComments(prev=>prev?`${prev}\n${breakdownText}`:breakdownText);setShowCalculator(false);};
  const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setError(null);if(!requesterName.trim()){setError('Por favor ingrese el Nombre del solicitante.');return;}if(!department.trim()){setError('Por favor seleccione o ingrese el Área o departamento.');return;}if(!requestType.trim()){setError('Por favor seleccione el Tipo de solicitud.');return;}if(!detail.trim()){setError('Por favor proporcione la Descripción/detalle de lo solicitado.');return;}if(!requestDate.trim()){setError('Por favor indique la Fecha de la solicitud.');return;}if(!depositDate.trim()){setError('Por favor indique la Fecha requerida de depósito.');return;}if(!urgency){setError('Por favor seleccione el nivel de Urgencia (baja / media / alta).');return;}if(!bossEmail.trim()){setError('Por favor seleccione el jefe o líder que autoriza.');return;}const isTravelType=requestType.toLowerCase().includes('viático')||requestType.toLowerCase().includes('viaje');if(isTravelType&&travelDays<0){setError('La fecha de fin debe ser posterior o igual a la fecha de inicio.');return;}const numAmount=amountRequested?parseFloat(amountRequested):0;if(isNaN(numAmount)||numAmount<0){setError('Por favor ingrese un monto estimado válido.');return;}setLoading(true);try{const data=await safeFetchJson<any>('/api/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requesterName:requesterName.trim(),department:department.trim(),requestType:requestType.trim(),detail:detail.trim(),requestDate:requestDate.trim(),depositDate:depositDate.trim(),urgency,bossId:selectedBossId||undefined,bossEmail:bossEmail.trim(),startDate:isTravelType?new Date(startDate).toISOString():new Date(requestDate).toISOString(),endDate:isTravelType?new Date(endDate).toISOString():new Date(requestDate).toISOString(),destination:destination.trim()||(isTravelType?'No especificado':'Sede Central Dimer'),reason:detail.trim(),amountRequested:numAmount,transportCost:isTravelType?calcTransport:0,hotelCost:isTravelType?calcHotel:0,foodCost:isTravelType?calcFood:0,miscCost:isTravelType?calcMisc:0,comments:comments.trim()})});
      // El backend devuelve directamente la solicitud creada (no envuelta en { request }).
      // Aceptamos ambos formatos para mantener compatibilidad si alguna versión del backend los usa.
      const createdRequest: TravelRequest | null = data?.request ?? (data?.id && data?.folio ? data as TravelRequest : null);
      if (!createdRequest) throw new Error(data?.error || 'El servidor no devolvió la solicitud creada.');
      const automationPayload={estado:'pendiente_autorizacion',correo_autorizacion:bossEmail.trim(),asunto:`Nueva solicitud por autorizar - ${requestType.trim()}`,cuerpo:`Se ha registrado una nueva solicitud en la plataforma Dimer.\n\n• Solicitante: ${requesterName.trim()}\n• Área/Departamento: ${department.trim()}\n• Tipo de Solicitud: ${requestType.trim()}\n• Fecha: ${requestDate.trim()}\n• Urgencia: ${urgency.toUpperCase()}\n• Detalle de lo solicitado:\n${detail.trim()}\n${numAmount>0?`• Monto Estimado: $${numAmount.toLocaleString('es-MX')} MXN\n`:''}• Supervisor que Autoriza: ${bossName} (${bossEmail.trim()})\n• Folio Oficial: ${createdRequest.folio}`,solicitud:{nombre:requesterName.trim(),area:department.trim(),tipo:requestType.trim(),detalle:detail.trim(),fecha:requestDate.trim(),urgency}};
      const notification = data?.notification;
      if (notification && notification.ok === false) {
        const details = Array.isArray(notification.errors) ? notification.errors.join(' | ') : 'No fue posible enviar las notificaciones.';
        throw new Error(`La solicitud ${createdRequest.folio} fue guardada, pero falló el envío de correo: ${details}`);
      }
      setSuccessResult({request:createdRequest,approvalToken:createdRequest.approvalToken,mailResult:notification,automationJson:automationPayload});
      onRequestCreated(createdRequest);
    }catch(err:any){setError(err.message||'Ocurrió un error inesperado.');}finally{setLoading(false);}};
  const handleCopyJson=()=>{if(successResult?.automationJson){navigator.clipboard.writeText(JSON.stringify(successResult.automationJson,null,2));setCopiedJson(true);setTimeout(()=>setCopiedJson(false),2500);}};
  const formatCurrency=(val:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(val);
  return (
    <div className="max-w-5xl mx-auto space-y-5 pb-6">
      {successResult ? (
        <div className="bg-white rounded-2xl shadow-lg shadow-slate-200/70 border border-emerald-200 overflow-hidden animate-in fade-in zoom-in-95 duration-200">
          <div className="bg-gradient-to-r from-slate-950 via-slate-900 to-slate-800 p-5 sm:p-6 text-white border-b border-emerald-500/40 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div className="flex items-center gap-3"><div className="w-11 h-11 bg-emerald-500/15 text-emerald-400 rounded-xl flex items-center justify-center border border-emerald-500/40 shadow-inner"><CheckCircle2 className="w-6 h-6 text-emerald-400" /></div><div><span className="text-[10px] uppercase font-bold tracking-[0.18em] text-emerald-400 font-mono">SOLICITUD REGISTRADA CORRECTAMENTE</span><h2 className="text-xl sm:text-2xl font-black font-mono tracking-tight">FOLIO: {successResult.request.folio}</h2></div></div>
            <div className="text-left sm:text-right"><span className={`inline-flex px-3 py-1.5 rounded-full text-[10px] font-bold uppercase tracking-wide ${urgency==='alta'?'bg-rose-500/20 text-rose-300 border border-rose-500/40':urgency==='baja'?'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40':'bg-amber-500/20 text-amber-300 border border-amber-500/40'}`}>Urgencia: {urgency.toUpperCase()}</span></div>
          </div>
          <div className="p-4 sm:p-6 space-y-4">
            <div className="bg-slate-50 p-4 sm:p-5 rounded-xl border border-slate-200 text-xs space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-200 pb-3"><span className="font-bold text-slate-800 uppercase tracking-wider text-[11px] flex items-center gap-1.5"><Layers className="w-3.5 h-3.5 text-indigo-600" />Datos de la Solicitud</span><span className="inline-flex w-fit px-2 py-1 rounded-md bg-amber-50 border border-amber-200 text-[10px] text-amber-700 font-mono font-bold">pendiente_autorizacion</span></div>
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-3">
                <div className="bg-white rounded-lg border border-slate-200 p-3"><span className="text-slate-500 block text-[10px] font-bold uppercase mb-1">1. Nombre del Solicitante</span><span className="font-semibold text-slate-900 break-words">{successResult.request.requesterName||requesterName}</span></div>
                <div className="bg-white rounded-lg border border-slate-200 p-3"><span className="text-slate-500 block text-[10px] font-bold uppercase mb-1">2. Área o Departamento</span><span className="font-semibold text-slate-900 break-words">{successResult.request.department||department}</span></div>
                <div className="bg-white rounded-lg border border-slate-200 p-3"><span className="text-slate-500 block text-[10px] font-bold uppercase mb-1">3. Tipo de Solicitud</span><span className="font-semibold text-indigo-700 break-words">{successResult.request.requestType||requestType}</span></div>
                <div className="bg-white rounded-lg border border-slate-200 p-3"><span className="text-slate-500 block text-[10px] font-bold uppercase mb-1">4. Fecha de la Solicitud</span><span className="font-semibold text-slate-900">{successResult.request.requestDate||requestDate}</span></div>
                <div className="bg-white rounded-lg border border-slate-200 p-3"><span className="text-slate-500 block text-[10px] font-bold uppercase mb-1">5. Urgencia</span><span className={`inline-block font-bold text-[11px] px-2 py-1 rounded-md capitalize ${urgency==='alta'?'bg-rose-100 text-rose-800':urgency==='baja'?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-800'}`}>{successResult.request.urgency||urgency}</span></div>
                <div className="bg-white rounded-lg border border-slate-200 p-3"><span className="text-slate-500 block text-[10px] font-bold uppercase mb-1">Supervisor que Autoriza</span><span className="font-mono text-indigo-800 font-semibold break-all">{successResult.request.bossEmail}</span></div>
              </div>
              <div className="pt-3 border-t border-slate-200"><span className="text-slate-500 block text-[10px] font-bold uppercase mb-1.5">6. Descripción / Detalle</span><p className="bg-white p-3 rounded-lg border border-slate-200 text-slate-800 whitespace-pre-line leading-relaxed font-sans">{successResult.request.detail||successResult.request.reason||detail}</p></div>
              {successResult.request.amountRequested>0&&<div className="pt-3 flex flex-col sm:flex-row sm:justify-between sm:items-center gap-2 border-t border-slate-200"><span className="text-slate-600 font-medium">Monto Total Estimado</span><span className="font-bold text-emerald-700 text-base">{formatCurrency(successResult.request.amountRequested)} MXN</span></div>}
            </div>
            <div className="p-4 bg-indigo-50 border border-indigo-200 rounded-xl text-xs text-indigo-950 shadow-sm"><div className="flex items-start gap-2.5"><div className="w-8 h-8 rounded-lg bg-indigo-100 flex items-center justify-center shrink-0"><Mail className="w-4 h-4 text-indigo-600" /></div><div><p className="font-bold">Notificación enviada para autorización</p><p className="text-[11px] text-indigo-700 mt-0.5">Se envió la solicitud a <strong>{successResult.request.bossEmail}</strong> para autorización. El resultado de la autorización se notificará únicamente al solicitante y a Finanzas.</p></div></div></div>
            <div className="flex flex-col sm:flex-row gap-2.5 pt-1"><button type="button" onClick={()=>{setSuccessResult(null);setDetail('');setDestination('');setAmountRequested('');setComments('');}} className="flex-1 py-2.5 px-3 border border-slate-300 rounded-xl font-semibold text-slate-700 hover:bg-slate-50 hover:border-slate-400 text-xs text-center transition cursor-pointer">Crear Otra Solicitud</button>{currentUser&&onLogout&&<button type="button" onClick={onLogout} className="flex-1 py-2.5 px-3 bg-rose-50 hover:bg-rose-100 text-rose-700 border border-rose-300 rounded-xl font-bold text-xs shadow-sm flex items-center justify-center gap-1.5 transition cursor-pointer" title="Cerrar sesión al finalizar mi solicitud"><LogOut className="w-3.5 h-3.5" /><span>Cerrar Sesión</span></button>}<button type="button" onClick={()=>onNavigateToApprovals(successResult.request.id)} className="flex-1 py-2.5 px-3 bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 text-white rounded-xl font-bold text-xs shadow-sm shadow-indigo-200 flex items-center justify-center gap-1.5 transition cursor-pointer"><span>Ver Módulo de Autorización</span><ArrowRight className="w-3.5 h-3.5" /></button></div>
          </div>
        </div>
      ) : (
        <div className="bg-white rounded-2xl shadow-lg shadow-slate-200/60 border border-slate-200 overflow-hidden">
          <div className="bg-gradient-to-r from-slate-950 via-slate-900 to-slate-800 p-5 sm:p-6 text-white flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-700">
            <div><div className="flex flex-wrap items-center gap-2"><span className="px-2.5 py-1 rounded-md bg-indigo-500/20 text-indigo-300 text-[10px] font-bold border border-indigo-500/30 uppercase font-mono tracking-wide">Dimer Viáticos</span><span className="text-[10px] text-slate-400 font-mono tracking-wide">SOLICITUD & AUTORIZACIÓN</span></div><h1 className="text-xl sm:text-2xl font-black text-white mt-2 tracking-tight">Solicitud de Viáticos</h1><p className="text-xs sm:text-sm text-slate-300 mt-1 max-w-2xl">Capture los datos necesarios para registrar la solicitud y enviar automáticamente la autorización.</p></div>
            {currentUser&&<div className="flex items-center gap-2 self-start sm:self-center"><div className="hidden sm:flex items-center gap-2 bg-slate-800/80 px-3 py-2 rounded-xl border border-slate-700"><ShieldCheck className="w-4 h-4 text-emerald-400" /><div className="text-[10px]"><div className="text-slate-400">Usuario Autenticado</div><div className="font-bold text-white truncate max-w-[160px]">{currentUser.name}</div></div></div>{onLogout&&<button type="button" onClick={onLogout} className="px-3 py-2 bg-rose-950/60 hover:bg-rose-900 text-rose-200 text-xs font-bold rounded-xl border border-rose-700/60 transition flex items-center gap-1.5 cursor-pointer" title="Cerrar sesión activa"><LogOut className="w-3.5 h-3.5" /><span className="hidden sm:inline">Cerrar Sesión</span><span className="sm:hidden">Salir</span></button>}</div>}
          </div>
          {error&&<div className="mx-4 mt-4 sm:mx-5 p-3.5 bg-rose-50 border border-rose-200 text-rose-800 rounded-xl text-xs flex items-start gap-2 shadow-sm"><div className="w-7 h-7 rounded-lg bg-rose-100 flex items-center justify-center shrink-0"><AlertCircle className="w-4 h-4 text-rose-600" /></div><div className="pt-1">{error}</div></div>}
          <form onSubmit={handleSubmit} className="p-4 sm:p-5 lg:p-6 space-y-5 text-xs">
              <div className="mb-4 space-y-1">
                <label className="block text-[10px] font-bold uppercase tracking-wide text-slate-500">Fecha requerida de depósito</label>
                <input type="date" value={depositDate} onChange={(e)=>setDepositDate(e.target.value)} min={requestDate} className="w-full px-3 py-2 bg-white border border-slate-300 rounded-lg text-xs focus:outline-none focus:ring-1 focus:ring-indigo-500" required />
                <p className="text-[10px] text-slate-400">Finanzas utilizará esta fecha para programar el depósito.</p>
              </div>
            <div className="bg-slate-50/90 p-4 sm:p-5 rounded-xl border border-slate-200 space-y-4">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-200 pb-3"><span className="font-bold text-slate-800 text-[11px] flex items-center gap-1.5 uppercase tracking-wide"><Layers className="w-4 h-4 text-indigo-600" />1. Información de la Solicitud</span><span className="inline-flex w-fit px-2 py-1 rounded-md bg-indigo-50 border border-indigo-100 text-[10px] text-indigo-700 font-semibold">Campos requeridos para autorización</span></div>
              <div className="bg-indigo-50/80 p-3.5 rounded-xl border border-indigo-100"><EmailAutocompleteInput id="requester-directory-search" label="Buscar Empleado en Directorio Dimer (Opcional para autollenado)" value={directorySearch} onChange={(val,emp)=>{setDirectorySearch(val);if(emp){setRequesterName(emp.name);setDepartment(emp.department);}}} /></div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <label className="block"><span className="block font-bold text-slate-700 mb-1.5">Nombre del Solicitante <span className="text-rose-500">*</span></span><input value={requesterName} onChange={e=>setRequesterName(e.target.value)} className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400" /></label>
                <label className="block"><span className="block font-bold text-slate-700 mb-1.5">Área o Departamento <span className="text-rose-500">*</span></span><select value={department} onChange={e=>setDepartment(e.target.value)} className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400"><option value="">Seleccione...</option>{departments.map(d=><option key={d.id} value={d.name}>{d.name}</option>)}{department&&!departments.some(d=>d.name===department)&&<option value={department}>{department}</option>}</select></label>
                <label className="block"><span className="block font-bold text-slate-700 mb-1.5">Tipo de Solicitud <span className="text-rose-500">*</span></span><select value={requestType} onChange={e=>setRequestType(e.target.value)} className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400">{requestTypes.map(t=><option key={t}>{t}</option>)}</select></label>
                <label className="block"><span className="block font-bold text-slate-700 mb-1.5">Fecha de la Solicitud <span className="text-rose-500">*</span></span><input type="date" value={requestDate} onChange={e=>setRequestDate(e.target.value)} className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400" /></label>
              </div>
              <div><span className="block font-bold text-slate-700 mb-1.5">Urgencia <span className="text-rose-500">*</span> <span className="font-normal text-slate-500">· Seleccione el nivel de prioridad</span></span><div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">{(['baja','media','alta'] as const).map(level=>{const active=urgency===level;const tone=level==='alta'?'rose':level==='baja'?'emerald':'amber';return <button key={level} type="button" onClick={()=>setUrgency(level)} className={`py-2.5 rounded-xl border font-bold transition cursor-pointer flex items-center justify-center gap-1.5 ${active?(tone==='rose'?'border-rose-400 bg-rose-50 text-rose-800 ring-2 ring-rose-100':tone==='emerald'?'border-emerald-400 bg-emerald-50 text-emerald-800 ring-2 ring-emerald-100':'border-amber-400 bg-amber-50 text-amber-800 ring-2 ring-amber-100'):'border-slate-300 bg-white text-slate-600 hover:border-slate-400 hover:bg-slate-50'}`}><span className="inline-block w-2 h-2 rounded-full bg-current" />{level[0].toUpperCase()+level.slice(1)}</button>})}</div></div>
              <label className="block"><span className="block font-bold text-slate-700 mb-1.5">Descripción / Detalle de lo Solicitado <span className="text-rose-500">*</span></span><textarea value={detail} onChange={e=>setDetail(e.target.value)} rows={4} placeholder="Describa claramente qué necesita, para qué se requiere y cualquier dato relevante..." className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition resize-y focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400 placeholder:text-slate-400" /></label>
            </div>
            <div className="bg-white border border-slate-200 rounded-xl p-4 sm:p-5 shadow-sm">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 mb-4"><div><span className="font-bold text-slate-800 text-[11px] uppercase tracking-wide">2. Responsable de Autorización <span className="text-rose-500">*</span></span><p className="text-[10px] text-slate-500 mt-0.5">El responsable recibirá la notificación de autorización.</p></div><span className="inline-flex w-fit px-2 py-1 rounded-md bg-emerald-50 border border-emerald-100 text-[10px] text-emerald-700 font-semibold">Notificación directa</span></div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><label className="block"><span className="block font-bold text-slate-700 mb-1.5">Seleccionar Responsable</span><select value={selectedBossId} onChange={e=>handleBossChange(e.target.value)} className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400">{bosses.map(b=><option key={b.id} value={b.id}>{b.name} — {b.department}</option>)}</select></label><label className="block"><span className="block font-bold text-slate-700 mb-1.5">Correo para Notificación</span><div className="relative"><Mail className="absolute left-3 top-3 w-4 h-4 text-slate-400" /><input value={bossEmail} readOnly className="w-full border border-slate-300 rounded-xl pl-9 pr-3 py-2.5 bg-slate-100 text-slate-700 cursor-not-allowed" /></div></label></div>
            </div>
            <div className="bg-indigo-50/50 border border-indigo-100 rounded-xl p-4 sm:p-5">
              <div className="flex items-center gap-2 mb-4"><div className="w-8 h-8 rounded-lg bg-indigo-100 flex items-center justify-center"><Calendar className="w-4 h-4 text-indigo-600" /></div><div><span className="font-bold text-slate-800 text-[11px] uppercase tracking-wide">3. Datos del Viaje y Presupuesto</span><p className="text-[10px] text-slate-500 mt-0.5">Fechas, destino y monto estimado de la solicitud.</p></div></div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4"><label><span className="block font-bold text-slate-700 mb-1.5">Fecha de Inicio de Viaje <span className="text-rose-500">*</span></span><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400" /></label><label><span className="block font-bold text-slate-700 mb-1.5">Fecha de Fin de Viaje <span className="text-rose-500">*</span></span><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400" /></label><label><span className="block font-bold text-slate-700 mb-1.5">Destino <span className="text-rose-500">*</span></span><input list="popular-destinations" value={destination} onChange={e=>setDestination(e.target.value)} placeholder="Ciudad, Estado / Sede / Cliente" className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400" /><datalist id="popular-destinations">{popularDestinations.map(d=><option key={d} value={d} />)}</datalist></label><label><span className="block font-bold text-slate-700 mb-1.5">Monto Estimado (MXN)</span><div className="flex gap-2"><input type="number" min="0" step="0.01" value={amountRequested} onChange={e=>setAmountRequested(e.target.value)} placeholder="0.00" className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400" /><button type="button" onClick={()=>setShowCalculator(v=>!v)} className="px-3.5 border border-indigo-200 bg-white hover:bg-indigo-50 hover:border-indigo-300 rounded-xl text-indigo-700 font-bold transition cursor-pointer" title="Abrir calculadora"><Calculator className="w-4 h-4" /></button></div></label></div>
            </div>
            {showCalculator&&<div className="bg-slate-900 text-white rounded-xl p-4 sm:p-5 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-3 shadow-lg"><div className="sm:col-span-2 md:col-span-4 flex items-center justify-between border-b border-slate-700 pb-3"><span className="font-bold text-xs flex items-center gap-2"><Calculator className="w-4 h-4 text-indigo-300" />Calculadora de Presupuesto</span><span className="text-[10px] text-slate-400">Distribuya el gasto estimado</span></div><label><span className="block text-[10px] text-slate-400 mb-1">Hospedaje</span><input type="number" value={calcHotel} onChange={e=>setCalcHotel(Number(e.target.value))} className="w-full bg-slate-800 border border-slate-700 rounded-lg px-2.5 py-2 text-xs text-white outline-none focus:border-indigo-400" /></label><label><span className="block text-[10px] text-slate-400 mb-1">Transporte</span><input type="number" value={calcTransport} onChange={e=>setCalcTransport(Number(e.target.value))} className="w-full bg-slate-800 border border-slate-700 rounded-lg px-2.5 py-2 text-xs text-white outline-none focus:border-indigo-400" /></label><label><span className="block text-[10px] text-slate-400 mb-1">Alimentos</span><input type="number" value={calcFood} onChange={e=>setCalcFood(Number(e.target.value))} className="w-full bg-slate-800 border border-slate-700 rounded-lg px-2.5 py-2 text-xs text-white outline-none focus:border-indigo-400" /></label><label><span className="block text-[10px] text-slate-400 mb-1">Imprevistos / Taxis</span><input type="number" value={calcMisc} onChange={e=>setCalcMisc(Number(e.target.value))} className="w-full bg-slate-800 border border-slate-700 rounded-lg px-2.5 py-2 text-xs text-white outline-none focus:border-indigo-400" /></label><button type="button" onClick={applyCalculatorTotal} className="col-span-1 sm:col-span-2 md:col-span-4 bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 py-2.5 rounded-lg font-bold text-xs transition cursor-pointer">Aplicar Total al Monto</button></div>}
            <div className="bg-white border border-slate-200 rounded-xl p-4 sm:p-5 shadow-sm"><label><span className="block font-bold text-slate-700 mb-1.5">Comentarios Adicionales</span><textarea value={comments} onChange={e=>setComments(e.target.value)} rows={3} placeholder="Información adicional, observaciones o instrucciones especiales..." className="w-full border border-slate-300 rounded-xl px-3 py-2.5 bg-white text-slate-900 outline-none transition resize-y focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100 hover:border-slate-400 placeholder:text-slate-400" /></label></div>
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-3 pt-1"><div className="text-[10px] text-slate-500 flex items-center gap-1.5 bg-slate-50 border border-slate-200 rounded-lg px-3 py-2"><ShieldCheck className="w-3.5 h-3.5 text-emerald-600 shrink-0" />La solicitud se registra y el correo de autorización se envía automáticamente.</div><button type="submit" disabled={loading} className="bg-indigo-600 hover:bg-indigo-500 active:bg-indigo-700 disabled:bg-slate-400 text-white px-6 py-3 rounded-xl font-bold text-xs flex items-center justify-center gap-2 cursor-pointer disabled:cursor-not-allowed shadow-sm shadow-indigo-200 transition sm:min-w-[190px]">{loading?<><Clock className="w-4 h-4 animate-spin" />Enviando...</>:<><Send className="w-4 h-4" />Enviar Solicitud</>}</button></div>
          </form>
        </div>
      )}
    </div>
  );
}
